SET SCAN OFF;
PROMPT Creating User pos2 ...
CREATE USER pos2 IDENTIFIED BY pos2 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SYNONYM TO pos2;
connect pos2/pos2;

-- DROP SEQUENCE crl_dept_stk_his_DEPARTMENT_ST;


PROMPT Creating Sequence crl_dept_stk_his_DEPARTMENT_ST ...
CREATE SEQUENCE  crl_dept_stk_his_DEPARTMENT_ST  
  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;

-- DROP SEQUENCE crl_mn_stk_his_STOCK_HISTORY_I;


PROMPT Creating Sequence crl_mn_stk_his_STOCK_HISTORY_I ...
CREATE SEQUENCE  crl_mn_stk_his_STOCK_HISTORY_I  
  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;

-- DROP SEQUENCE crl_pos_log_Id_SEQ;


PROMPT Creating Sequence crl_pos_log_Id_SEQ ...
CREATE SEQUENCE  crl_pos_log_Id_SEQ  
  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;

-- DROP SEQUENCE temp_dept_stock_statistics_tem;


PROMPT Creating Sequence temp_dept_stock_statistics_tem ...
CREATE SEQUENCE  temp_dept_stock_statistics_tem  
  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1  NOCYCLE ;

-- DROP TABLE crl_cat CASCADE CONSTRAINTS;


PROMPT Creating Table crl_cat ...
CREATE TABLE crl_cat (
  CATEGORY_ID NUMBER(10,0) NOT NULL,
  PARENT_CATEGORY_ID NUMBER(10,0),
  CATEGORY_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_88 on table crl_cat ... 
ALTER TABLE crl_cat
ADD CONSTRAINT PRIMARY_88 PRIMARY KEY
(
  CATEGORY_ID
)
ENABLE
;

-- DROP TABLE crl_dept_stk_in CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk_in ...
CREATE TABLE crl_dept_stk_in (
  STOCK_IN_ID VARCHAR2(15 CHAR) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  STOCK_IN_DATE DATE,
  DESCRIPTION VARCHAR2(2000 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  EXPORT_STATUS NUMBER(10,0) DEFAULT '0',
  STOCK_IN_COST NUMBER(10,0) DEFAULT '0',
  STOCK_IN_TYPE NUMBER(10,0) DEFAULT '0'
);


COMMENT ON COLUMN crl_dept_stk_in.STOCK_IN_TYPE IS '1 : ReStock ; 0: Normal'
;

PROMPT Creating Primary Key Constraint PRIMARY_110 on table crl_dept_stk_in ... 
ALTER TABLE crl_dept_stk_in
ADD CONSTRAINT PRIMARY_110 PRIMARY KEY
(
  STOCK_IN_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index Index_5_7 on crl_dept_stk_in ...
CREATE INDEX Index_5_7 ON crl_dept_stk_in
(
  CREATE_DATE
) 
;
PROMPT Creating Index Index_2_7 on crl_dept_stk_in ...
CREATE INDEX Index_2_7 ON crl_dept_stk_in
(
  STOCK_IN_ID,
  DEPARTMENT_ID
) 
;
PROMPT Creating Index Index_3_16 on crl_dept_stk_in ...
CREATE INDEX Index_3_16 ON crl_dept_stk_in
(
  STOCK_IN_ID
) 
;
PROMPT Creating Index Index_4_18 on crl_dept_stk_in ...
CREATE INDEX Index_4_18 ON crl_dept_stk_in
(
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_ex_prd_color CASCADE CONSTRAINTS;


PROMPT Creating Table crl_ex_prd_color ...
CREATE TABLE crl_ex_prd_color (
  COLOR_ID NUMBER(10,0) NOT NULL,
  COLOR_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_127 on table crl_ex_prd_color ... 
ALTER TABLE crl_ex_prd_color
ADD CONSTRAINT PRIMARY_127 PRIMARY KEY
(
  COLOR_ID
)
ENABLE
;

-- DROP TABLE crl_prd_typ CASCADE CONSTRAINTS;


PROMPT Creating Table crl_prd_typ ...
CREATE TABLE crl_prd_typ (
  TYPE_ID NUMBER(10,0) NOT NULL,
  TYPE_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_141 on table crl_prd_typ ... 
ALTER TABLE crl_prd_typ
ADD CONSTRAINT PRIMARY_141 PRIMARY KEY
(
  TYPE_ID
)
ENABLE
;

-- DROP TABLE crl_role CASCADE CONSTRAINTS;


PROMPT Creating Table crl_role ...
CREATE TABLE crl_role (
  id NUMBER(10,0) NOT NULL,
  name VARCHAR2(50 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_150 on table crl_role ... 
ALTER TABLE crl_role
ADD CONSTRAINT PRIMARY_150 PRIMARY KEY
(
  id
)
ENABLE
;

-- DROP TABLE crl_sale_trans CASCADE CONSTRAINTS;


PROMPT Creating Table crl_sale_trans ...
CREATE TABLE crl_sale_trans (
  Sale_Transaction_Id VARCHAR2(10 CHAR) NOT NULL,
  Transaction_Id VARCHAR2(12 CHAR) NOT NULL,
  POS_Transaction_Id VARCHAR2(10 CHAR) NOT NULL,
  Store_Id VARCHAR2(5 CHAR) NOT NULL,
  Register_Id VARCHAR2(2 CHAR) NOT NULL,
  Cashier_Id VARCHAR2(6 CHAR) NOT NULL,
  Purchase_Order_Id VARCHAR2(15 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_151 on table crl_sale_trans ... 
ALTER TABLE crl_sale_trans
ADD CONSTRAINT PRIMARY_151 PRIMARY KEY
(
  Sale_Transaction_Id
)
ENABLE
;

-- DROP TABLE crl_sche_tmplate CASCADE CONSTRAINTS;


PROMPT Creating Table crl_sche_tmplate ...
CREATE TABLE crl_sche_tmplate (
  EMPLOYEE_ID VARCHAR2(20 CHAR) NOT NULL,
  SCHEDULE_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  MONDAY NUMBER(10,0),
  TUESDAY NUMBER(10,0),
  WEDNESDAY NUMBER(10,0),
  THURSDAY NUMBER(10,0),
  FRIDAY NUMBER(10,0),
  SATURDAY NUMBER(10,0),
  SUNDAY NUMBER(10,0),
  DEL_FLG NUMBER(10,0),
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  START_DATE DATE,
  END_DATE DATE,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0)
);


PROMPT Creating Primary Key Constraint PRIMARY_152 on table crl_sche_tmplate ... 
ALTER TABLE crl_sche_tmplate
ADD CONSTRAINT PRIMARY_152 PRIMARY KEY
(
  EMPLOYEE_ID,
  SCHEDULE_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index SCHEDULE_TEMPLATE_FKIndex1 on crl_sche_tmplate ...
CREATE INDEX SCHEDULE_TEMPLATE_FKIndex1 ON crl_sche_tmplate
(
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_sim_prd CASCADE CONSTRAINTS;


PROMPT Creating Table crl_sim_prd ...
CREATE TABLE crl_sim_prd (
  BASE_PRODUCT_ID NUMBER(10,0) NOT NULL,
  OTHER_PRODUCT_ID NUMBER(10,0) NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_153 on table crl_sim_prd ... 
ALTER TABLE crl_sim_prd
ADD CONSTRAINT PRIMARY_153 PRIMARY KEY
(
  BASE_PRODUCT_ID,
  OTHER_PRODUCT_ID
)
ENABLE
;

-- DROP TABLE crl_stk_def_stat CASCADE CONSTRAINTS;


PROMPT Creating Table crl_stk_def_stat ...
CREATE TABLE crl_stk_def_stat (
  DEFECT_STATUS_ID NUMBER(10,0) NOT NULL,
  DEFECT_STATUS_NAME VARCHAR2(200 CHAR) NOT NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_154 on table crl_stk_def_stat ... 
ALTER TABLE crl_stk_def_stat
ADD CONSTRAINT PRIMARY_154 PRIMARY KEY
(
  DEFECT_STATUS_ID
)
ENABLE
;

-- DROP TABLE crl_stk_in CASCADE CONSTRAINTS;


PROMPT Creating Table crl_stk_in ...
CREATE TABLE crl_stk_in (
  STOCK_IN_ID VARCHAR2(11 CHAR) NOT NULL,
  STOCK_IN_DATE DATE,
  CREATE_DATE DATE,
  DESCRIPTION VARCHAR2(2000 CHAR),
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  STOCK_IN_COST NUMBER(10,0) DEFAULT '0',
  STOCK_IN_TYPE NUMBER(10,0),
  CONFIRM_FLG NUMBER(10,0) DEFAULT '0'
);


PROMPT Creating Primary Key Constraint PRIMARY_155 on table crl_stk_in ... 
ALTER TABLE crl_stk_in
ADD CONSTRAINT PRIMARY_155 PRIMARY KEY
(
  STOCK_IN_ID
)
ENABLE
;
PROMPT Creating Index INDEX_2_8_3 on crl_stk_in ...
CREATE INDEX INDEX_2_8_3 ON crl_stk_in
(
  STOCK_IN_DATE
) 
;
PROMPT Creating Index INDEX_3_22_3 on crl_stk_in ...
CREATE INDEX INDEX_3_22_3 ON crl_stk_in
(
  CREATE_DATE
) 
;

-- DROP TABLE crl_stk_in_det CASCADE CONSTRAINTS;


PROMPT Creating Table crl_stk_in_det ...
CREATE TABLE crl_stk_in_det (
  STOCK_IN_ID VARCHAR2(11 CHAR) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  QUANTITY NUMBER(10,0),
  PRICE NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  STOCK_IN_TYPE NUMBER(10,0),
  SELL_PRICE NUMBER(10,0)
);


PROMPT Creating Primary Key Constraint PRIMARY_156 on table crl_stk_in_det ... 
ALTER TABLE crl_stk_in_det
ADD CONSTRAINT PRIMARY_156 PRIMARY KEY
(
  STOCK_IN_ID,
  PRODUCT_ID
)
ENABLE
;
PROMPT Creating Index STOCK_IN_DETAIL_FKIndex1 on crl_stk_in_det ...
CREATE INDEX STOCK_IN_DETAIL_FKIndex1 ON crl_stk_in_det
(
  STOCK_IN_ID
) 
;
PROMPT Creating Index STOCK_IN_DETAIL_FKIndex2 on crl_stk_in_det ...
CREATE INDEX STOCK_IN_DETAIL_FKIndex2 ON crl_stk_in_det
(
  PRODUCT_ID
) 
;
PROMPT Creating Index Index_4_7 on crl_stk_in_det ...
CREATE INDEX Index_4_7 ON crl_stk_in_det
(
  PRODUCT_MASTER_ID
) 
;
PROMPT Creating Index Index_5_5 on crl_stk_in_det ...
CREATE INDEX Index_5_5 ON crl_stk_in_det
(
  PRODUCT_ID,
  PRODUCT_MASTER_ID
) 
;

-- DROP TABLE crl_stk_out CASCADE CONSTRAINTS;


PROMPT Creating Table crl_stk_out ...
CREATE TABLE crl_stk_out (
  STOCKOUT_ID NUMBER(10,0) NOT NULL,
  STOCK_OUT_DATE DATE,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  STOCK_ID NUMBER(10,0),
  DEFECT_STATUS_ID NUMBER(10,0),
  CONFIRM_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_157 on table crl_stk_out ... 
ALTER TABLE crl_stk_out
ADD CONSTRAINT PRIMARY_157 PRIMARY KEY
(
  STOCKOUT_ID
)
ENABLE
;
PROMPT Creating Index FK_stock_out_1 on crl_stk_out ...
CREATE INDEX FK_stock_out_1 ON crl_stk_out
(
  STOCK_ID
) 
;
PROMPT Creating Index fk_CRL_STK_OUT_CRL_DEPT1 on crl_stk_out ...
CREATE INDEX fk_CRL_STK_OUT_CRL_DEPT1 ON crl_stk_out
(
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_stk_out_cst CASCADE CONSTRAINTS;


PROMPT Creating Table crl_stk_out_cst ...
CREATE TABLE crl_stk_out_cst (
  STOCK_OUT_ID NUMBER(10,0) NOT NULL,
  COST_TYPE NUMBER(10,0) NOT NULL,
  STOCKOUT_ID NUMBER(10,0) NOT NULL,
  COST NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_158 on table crl_stk_out_cst ... 
ALTER TABLE crl_stk_out_cst
ADD CONSTRAINT PRIMARY_158 PRIMARY KEY
(
  STOCK_OUT_ID,
  COST_TYPE
)
ENABLE
;
PROMPT Creating Index STOCK_OUT_COST_FKIndex1 on crl_stk_out_cst ...
CREATE INDEX STOCK_OUT_COST_FKIndex1 ON crl_stk_out_cst
(
  STOCKOUT_ID
) 
;

-- DROP TABLE crl_stk_out_det CASCADE CONSTRAINTS;


PROMPT Creating Table crl_stk_out_det ...
CREATE TABLE crl_stk_out_det (
  STOCK_OUT_DETAIL_ID NUMBER(10,0) NOT NULL,
  STOCKOUT_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  QUANTITY NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  DEFECT_STATUS_ID NUMBER(10,0),
  DESCRIPTION VARCHAR2(500 CHAR),
  GOOD_QUANTITY NUMBER(10,0) DEFAULT '0',
  ERROR_QUANTITY NUMBER(10,0) DEFAULT '0',
  DAMAGE_QUANTITY NUMBER(10,0) DEFAULT '0',
  LOST_QUANTITY NUMBER(10,0) DEFAULT '0'
);


PROMPT Creating Primary Key Constraint PRIMARY_159 on table crl_stk_out_det ... 
ALTER TABLE crl_stk_out_det
ADD CONSTRAINT PRIMARY_159 PRIMARY KEY
(
  STOCK_OUT_DETAIL_ID
)
ENABLE
;
PROMPT Creating Index FK_stock_out_detail_1 on crl_stk_out_det ...
CREATE INDEX FK_stock_out_detail_1 ON crl_stk_out_det
(
  PRODUCT_ID
) 
;
PROMPT Creating Index Index_3_21 on crl_stk_out_det ...
CREATE INDEX Index_3_21 ON crl_stk_out_det
(
  STOCK_OUT_DETAIL_ID,
  STOCKOUT_ID,
  PRODUCT_MASTER_ID
) 
;
PROMPT Creating Index FK_stock_out on crl_stk_out_det ...
CREATE INDEX FK_stock_out ON crl_stk_out_det
(
  STOCKOUT_ID
) 
;

-- DROP TABLE crl_stk_out_tmp CASCADE CONSTRAINTS;


PROMPT Creating Table crl_stk_out_tmp ...
CREATE TABLE crl_stk_out_tmp (
  STOCKOUT_ID NUMBER(10,0) NOT NULL,
  STOCK_OUT_DATE DATE,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  STOCK_ID NUMBER(10,0),
  DEFECT_STATUS_ID NUMBER(10,0),
  CONFIRM_FLG NUMBER(10,0) DEFAULT '0'
);



-- DROP TABLE crl_sup CASCADE CONSTRAINTS;


PROMPT Creating Table crl_sup ...
CREATE TABLE crl_sup (
  SUPPLIER_ID NUMBER(10,0) NOT NULL,
  SUPPLIER_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_160 on table crl_sup ... 
ALTER TABLE crl_sup
ADD CONSTRAINT PRIMARY_160 PRIMARY KEY
(
  SUPPLIER_ID
)
ENABLE
;

-- DROP TABLE crl_sync_status CASCADE CONSTRAINTS;


PROMPT Creating Table crl_sync_status ...
CREATE TABLE crl_sync_status (
  LAST_SYNC_DATE DATE NOT NULL,
  CREATE_ID VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_161 on table crl_sync_status ... 
ALTER TABLE crl_sync_status
ADD CONSTRAINT PRIMARY_161 PRIMARY KEY
(
  LAST_SYNC_DATE
)
ENABLE
;

-- DROP TABLE crl_tax CASCADE CONSTRAINTS;


PROMPT Creating Table crl_tax ...
CREATE TABLE crl_tax (
  TAX_ID NUMBER(10,0) NOT NULL,
  TAX_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_162 on table crl_tax ... 
ALTER TABLE crl_tax
ADD CONSTRAINT PRIMARY_162 PRIMARY KEY
(
  TAX_ID
)
ENABLE
;

-- DROP TABLE crl_trans CASCADE CONSTRAINTS;


PROMPT Creating Table crl_trans ...
CREATE TABLE crl_trans (
  Transaction_Id VARCHAR2(12 CHAR) NOT NULL,
  Store_Id VARCHAR2(5 CHAR) NOT NULL,
  Register_Id VARCHAR2(2 CHAR) NOT NULL,
  Cashier_Id VARCHAR2(6 CHAR) NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  Transaction_Type NUMBER(10,0) NOT NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_163 on table crl_trans ... 
ALTER TABLE crl_trans
ADD CONSTRAINT PRIMARY_163 PRIMARY KEY
(
  Transaction_Id
)
ENABLE
;

-- DROP TABLE crl_usr_info CASCADE CONSTRAINTS;


PROMPT Creating Table crl_usr_info ...
CREATE TABLE crl_usr_info (
  Username VARCHAR2(50 CHAR) NOT NULL,
  Password VARCHAR2(50 CHAR),
  EMPLOYEE_ID VARCHAR2(20 CHAR),
  DEPARTMENT_ID NUMBER(10,0),
  SUSPENDED NUMBER(10,0) DEFAULT '0',
  DELETED NUMBER(10,0) DEFAULT '0'
);


PROMPT Creating Primary Key Constraint PRIMARY_164 on table crl_usr_info ... 
ALTER TABLE crl_usr_info
ADD CONSTRAINT PRIMARY_164 PRIMARY KEY
(
  Username
)
ENABLE
;

-- DROP TABLE crl_usr_role CASCADE CONSTRAINTS;


PROMPT Creating Table crl_usr_role ...
CREATE TABLE crl_usr_role (
  userid VARCHAR2(50 CHAR) NOT NULL,
  roleid NUMBER(10,0) NOT NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_165 on table crl_usr_role ... 
ALTER TABLE crl_usr_role
ADD CONSTRAINT PRIMARY_165 PRIMARY KEY
(
  userid,
  roleid
)
ENABLE
;
PROMPT Creating Index FK_UserRole_Role on crl_usr_role ...
CREATE INDEX FK_UserRole_Role ON crl_usr_role
(
  roleid
) 
;

-- DROP TABLE temp_dept_stock_statistics CASCADE CONSTRAINTS;


PROMPT Creating Table temp_dept_stock_statistics ...
CREATE TABLE temp_dept_stock_statistics (
  department_name VARCHAR2(500 CHAR),
  type_name VARCHAR2(500 CHAR),
  product_id VARCHAR2(20 CHAR) NOT NULL,
  product_name VARCHAR2(500 CHAR),
  color_name VARCHAR2(500 CHAR),
  size_name VARCHAR2(500 CHAR),
  prestk_qty FLOAT,
  instock_qty FLOAT,
  error_qty FLOAT,
  dmg_qty FLOAT,
  stkout_qty FLOAT,
  tmpout_qty FLOAT,
  rtn_qty FLOAT,
  destroy_qty FLOAT,
  bkpro FLOAT,
  realstock FLOAT,
  temp_pri_key NUMBER(10,0) NOT NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_166 on table temp_dept_stock_statistics ... 
ALTER TABLE temp_dept_stock_statistics
ADD CONSTRAINT PRIMARY_166 PRIMARY KEY
(
  temp_pri_key
)
ENABLE
;

-- DROP TABLE temp_deptstock CASCADE CONSTRAINTS;


PROMPT Creating Table temp_deptstock ...
CREATE TABLE temp_deptstock (
  TYPE_ID NUMBER(10,0) NOT NULL,
  TYPE_NAME VARCHAR2(500 CHAR),
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_NAME VARCHAR2(500 CHAR),
  COLOR_NAME VARCHAR2(500 CHAR),
  SIZE_NAME VARCHAR2(500 CHAR),
  PRICE NUMBER(10,0) DEFAULT '0' NOT NULL,
  department_name VARCHAR2(500 CHAR)
);


PROMPT Creating Index Index_1_18 on temp_deptstock ...
CREATE INDEX Index_1_18 ON temp_deptstock
(
  PRODUCT_ID
) 
;

-- DROP TABLE temp_deptstock_max_temp CASCADE CONSTRAINTS;


PROMPT Creating Table temp_deptstock_max_temp ...
CREATE TABLE temp_deptstock_max_temp (
  PRODUCT_ID VARCHAR2(20 CHAR),
  good_qty NUMBER(10,0) DEFAULT '0',
  perror_qty NUMBER(10,0) DEFAULT '0',
  predmg NUMBER(24,0)
);


PROMPT Creating Index Index_1_17 on temp_deptstock_max_temp ...
CREATE INDEX Index_1_17 ON temp_deptstock_max_temp
(
  PRODUCT_ID
) 
;

-- DROP TABLE temp_dp_stockout CASCADE CONSTRAINTS;


PROMPT Creating Table temp_dp_stockout ...
CREATE TABLE temp_dp_stockout (
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  DEFECT_STATUS_ID NUMBER(10,0),
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  quantity FLOAT
);


PROMPT Creating Index Index_1_16 on temp_dp_stockout ...
CREATE INDEX Index_1_16 ON temp_dp_stockout
(
  PRODUCT_ID,
  DEFECT_STATUS_ID
) 
;
PROMPT Creating Index Index_2_6 on temp_dp_stockout ...
CREATE INDEX Index_2_6 ON temp_dp_stockout
(
  DEFECT_STATUS_ID
) 
;

-- DROP TABLE temp_pr CASCADE CONSTRAINTS;


PROMPT Creating Table temp_pr ...
CREATE TABLE temp_pr (
  TYPE_ID NUMBER(10,0) NOT NULL,
  TYPE_NAME VARCHAR2(500 CHAR),
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_NAME VARCHAR2(500 CHAR),
  COLOR_NAME VARCHAR2(500 CHAR),
  SIZE_NAME VARCHAR2(500 CHAR),
  PRICE NUMBER(10,0) DEFAULT '0' NOT NULL
);


PROMPT Creating Index Index_1_15 on temp_pr ...
CREATE INDEX Index_1_15 ON temp_pr
(
  PRODUCT_ID,
  PRODUCT_MASTER_ID
) 
;

-- DROP TABLE temp_product CASCADE CONSTRAINTS;


PROMPT Creating Table temp_product ...
CREATE TABLE temp_product (
  TYPE_ID NUMBER(10,0) NOT NULL,
  TYPE_NAME VARCHAR2(500 CHAR),
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_NAME VARCHAR2(500 CHAR),
  COLOR_NAME VARCHAR2(500 CHAR),
  SIZE_NAME VARCHAR2(500 CHAR),
  PRICE NUMBER(10,0) DEFAULT '0' NOT NULL,
  department_name VARCHAR2(500 CHAR)
);


PROMPT Creating Index Index_1_14 on temp_product ...
CREATE INDEX Index_1_14 ON temp_product
(
  PRODUCT_ID
) 
;

-- DROP TABLE temp_stk_his CASCADE CONSTRAINTS;


PROMPT Creating Table temp_stk_his ...
CREATE TABLE temp_stk_his (
  PRODUCT_ID VARCHAR2(20 CHAR),
  good_qty NUMBER(10,0) DEFAULT '0',
  perror_qty NUMBER(10,0) DEFAULT '0',
  predmg NUMBER(24,0)
);


PROMPT Creating Index Index_1_13 on temp_stk_his ...
CREATE INDEX Index_1_13 ON temp_stk_his
(
  PRODUCT_ID
) 
;

-- DROP TABLE crl_blk_in CASCADE CONSTRAINTS;


PROMPT Creating Table crl_blk_in ...
CREATE TABLE crl_blk_in (
  BLOCK_ID NUMBER(10,0) NOT NULL,
  BLOCK_NAME VARCHAR2(500 CHAR),
  IMPORT_DATE DATE,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY on table crl_blk_in ... 
ALTER TABLE crl_blk_in
ADD CONSTRAINT PRIMARY PRIMARY KEY
(
  BLOCK_ID
)
ENABLE
;

-- DROP TABLE crl_blk_in_cost CASCADE CONSTRAINTS;


PROMPT Creating Table crl_blk_in_cost ...
CREATE TABLE crl_blk_in_cost (
  BLOCK_ID NUMBER(10,0) NOT NULL,
  COST_TYPE NUMBER(10,0) NOT NULL,
  COST NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_85 on table crl_blk_in_cost ... 
ALTER TABLE crl_blk_in_cost
ADD CONSTRAINT PRIMARY_85 PRIMARY KEY
(
  BLOCK_ID,
  COST_TYPE
)
ENABLE
;
PROMPT Creating Index BLOCK_IN_COST_FKIndex1 on crl_blk_in_cost ...
CREATE INDEX BLOCK_IN_COST_FKIndex1 ON crl_blk_in_cost
(
  BLOCK_ID
) 
;

-- DROP TABLE crl_blk_in_det CASCADE CONSTRAINTS;


PROMPT Creating Table crl_blk_in_det ...
CREATE TABLE crl_blk_in_det (
  BLOCK_ID NUMBER(10,0) NOT NULL,
  BLOCK_DETAIL_ID VARCHAR2(10 CHAR) NOT NULL,
  DETAIL_VALUE CLOB,
  MANUFACTURE_ID NUMBER(10,0),
  PACKAGER_ID NUMBER(10,0),
  COUNTRY_ID NUMBER(10,0),
  SUPPLIER_ID NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  STOCK_IN_ID NUMBER(10,0),
  IMPORT_DATE DATE
);


PROMPT Creating Primary Key Constraint PRIMARY_86 on table crl_blk_in_det ... 
ALTER TABLE crl_blk_in_det
ADD CONSTRAINT PRIMARY_86 PRIMARY KEY
(
  BLOCK_ID,
  BLOCK_DETAIL_ID
)
ENABLE
;
PROMPT Creating Index BLOCK_IN_DETAIL_FKIndex1 on crl_blk_in_det ...
CREATE INDEX BLOCK_IN_DETAIL_FKIndex1 ON crl_blk_in_det
(
  BLOCK_ID
) 
;

-- DROP TABLE crl_cash_io_trans CASCADE CONSTRAINTS;


PROMPT Creating Table crl_cash_io_trans ...
CREATE TABLE crl_cash_io_trans (
  Cash_In_Out_Transaction_Id VARCHAR2(15 CHAR) NOT NULL,
  Transaction_Id VARCHAR2(12 CHAR) NOT NULL,
  Store_Id VARCHAR2(5 CHAR) NOT NULL,
  Register_Id VARCHAR2(2 CHAR) NOT NULL,
  Cashier_Id VARCHAR2(6 CHAR) NOT NULL,
  Amount FLOAT,
  Reason_Code NUMBER(10,0),
  Customer_Id VARCHAR2(15 CHAR),
  Comment_ VARCHAR2(1000 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


COMMENT ON COLUMN crl_cash_io_trans.Comment_ IS 'ORIGINAL NAME:Comment'
;

PROMPT Creating Primary Key Constraint PRIMARY_87 on table crl_cash_io_trans ... 
ALTER TABLE crl_cash_io_trans
ADD CONSTRAINT PRIMARY_87 PRIMARY KEY
(
  Cash_In_Out_Transaction_Id
)
ENABLE
;

-- DROP TABLE crl_contract CASCADE CONSTRAINTS;


PROMPT Creating Table crl_contract ...
CREATE TABLE crl_contract (
  CONTRACT_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  CONTRACT_NAME VARCHAR2(500 CHAR),
  CONTRACT_TYPE NUMBER(10,0),
  START_DATE DATE,
  END_DATE DATE,
  EMPLOYEE_ID VARCHAR2(20 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_89 on table crl_contract ... 
ALTER TABLE crl_contract
ADD CONSTRAINT PRIMARY_89 PRIMARY KEY
(
  CONTRACT_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index CONTRACT_FKIndex1 on crl_contract ...
CREATE INDEX CONTRACT_FKIndex1 ON crl_contract
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_coupon CASCADE CONSTRAINTS;


PROMPT Creating Table crl_coupon ...
CREATE TABLE crl_coupon (
  COUPON_ID NUMBER(10,0) NOT NULL,
  COUPON_NAME VARCHAR2(500 CHAR),
  COUPON_TYPE NUMBER(10,0),
  DISCOUNT_VALUE NUMBER(10,0),
  DISCOUNT_PERCENT NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_90 on table crl_coupon ... 
ALTER TABLE crl_coupon
ADD CONSTRAINT PRIMARY_90 PRIMARY KEY
(
  COUPON_ID
)
ENABLE
;
PROMPT Creating Index COUPON_FKIndex1 on crl_coupon ...
CREATE INDEX COUPON_FKIndex1 ON crl_coupon
(
  COUPON_TYPE
) 
;

-- DROP TABLE crl_coupon_typ CASCADE CONSTRAINTS;


PROMPT Creating Table crl_coupon_typ ...
CREATE TABLE crl_coupon_typ (
  COUPON_TYPE_ID NUMBER(10,0) NOT NULL,
  COUPON_TYPE_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_91 on table crl_coupon_typ ... 
ALTER TABLE crl_coupon_typ
ADD CONSTRAINT PRIMARY_91 PRIMARY KEY
(
  COUPON_TYPE_ID
)
ENABLE
;

-- DROP TABLE crl_ctry CASCADE CONSTRAINTS;


PROMPT Creating Table crl_ctry ...
CREATE TABLE crl_ctry (
  COUNTRY_ID NUMBER(10,0) NOT NULL,
  COUNTRY_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_92 on table crl_ctry ... 
ALTER TABLE crl_ctry
ADD CONSTRAINT PRIMARY_92 PRIMARY KEY
(
  COUNTRY_ID
)
ENABLE
;

-- DROP TABLE crl_cust CASCADE CONSTRAINTS;


PROMPT Creating Table crl_cust ...
CREATE TABLE crl_cust (
  CUSTOMER_ID NUMBER(10,0) NOT NULL,
  CUSTOMER_NAME VARCHAR2(500 CHAR),
  MONEY_SPENT NUMBER(10,0),
  BUY_COUNT NUMBER(10,0),
  NEAREST_COME_1 DATE,
  NEAREST_COME_2 DATE,
  NEAREST_COME_3 DATE,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_93 on table crl_cust ... 
ALTER TABLE crl_cust
ADD CONSTRAINT PRIMARY_93 PRIMARY KEY
(
  CUSTOMER_ID
)
ENABLE
;

-- DROP TABLE crl_cust_det CASCADE CONSTRAINTS;


PROMPT Creating Table crl_cust_det ...
CREATE TABLE crl_cust_det (
  CUSTOMER_ID NUMBER(10,0) NOT NULL,
  ADDRESS VARCHAR2(500 CHAR),
  COUNTRY_ID NUMBER(10,0),
  BIRTHDAY DATE,
  PASSPORT_NUMBER VARCHAR2(500 CHAR),
  CMND VARCHAR2(500 CHAR),
  MONEY_SPENT NUMBER(10,0),
  BUY_COUNT NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0'
);


PROMPT Creating Primary Key Constraint PRIMARY_94 on table crl_cust_det ... 
ALTER TABLE crl_cust_det
ADD CONSTRAINT PRIMARY_94 PRIMARY KEY
(
  CUSTOMER_ID
)
ENABLE
;

-- DROP TABLE crl_dept CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept ...
CREATE TABLE crl_dept (
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_NAME VARCHAR2(500 CHAR),
  ADDRESS VARCHAR2(500 CHAR),
  ACTIVE NUMBER(10,0) DEFAULT '0',
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  START_DATE DATE
);


PROMPT Creating Primary Key Constraint PRIMARY_95 on table crl_dept ... 
ALTER TABLE crl_dept
ADD CONSTRAINT PRIMARY_95 PRIMARY KEY
(
  DEPARTMENT_ID
)
ENABLE
;

-- DROP TABLE crl_dept_cost CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_cost ...
CREATE TABLE crl_dept_cost (
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  COST_DATE DATE NOT NULL,
  COST_TYPE NUMBER(10,0),
  COST_NAME VARCHAR2(500 CHAR),
  COST_DESCRIPTION CLOB,
  COST NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_96 on table crl_dept_cost ... 
ALTER TABLE crl_dept_cost
ADD CONSTRAINT PRIMARY_96 PRIMARY KEY
(
  DEPARTMENT_ID,
  COST_DATE
)
ENABLE
;
PROMPT Creating Index DEPARTMENT_COST_FKIndex1 on crl_dept_cost ...
CREATE INDEX DEPARTMENT_COST_FKIndex1 ON crl_dept_cost
(
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_dept_mng CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_mng ...
CREATE TABLE crl_dept_mng (
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  EMPLOYEE_ID VARCHAR2(20 CHAR) NOT NULL,
  POSITION NUMBER(10,0) DEFAULT '0',
  CREATE_ID VARCHAR2(45 CHAR),
  CREATE_DATE DATE,
  UPDATE_ID VARCHAR2(45 CHAR),
  UPDATE_DATE DATE,
  WORKING_DAY DATE NOT NULL,
  START_TIME DATE,
  END_TIME DATE,
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


COMMENT ON COLUMN crl_dept_mng.POSITION IS '0: Normal ; 1: Manager'
;

PROMPT Creating Primary Key Constraint PRIMARY_97 on table crl_dept_mng ... 
ALTER TABLE crl_dept_mng
ADD CONSTRAINT PRIMARY_97 PRIMARY KEY
(
  DEPARTMENT_ID,
  EMPLOYEE_ID,
  WORKING_DAY
)
ENABLE
;
PROMPT Creating Index fk_crl_dept_mng_crl_dept1 on crl_dept_mng ...
CREATE INDEX fk_crl_dept_mng_crl_dept1 ON crl_dept_mng
(
  DEPARTMENT_ID
) 
;
PROMPT Creating Index fk_crl_dept_mng_crl_emp_info1 on crl_dept_mng ...
CREATE INDEX fk_crl_dept_mng_crl_emp_info1 ON crl_dept_mng
(
  EMPLOYEE_ID
) 
;

-- DROP TABLE crl_dept_po CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_po ...
CREATE TABLE crl_dept_po (
  PURCHASE_ORDER_ID VARCHAR2(20 CHAR) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PURCHASE_PRICE NUMBER(24,0),
  ORDER_STATUS NUMBER(10,0),
  CUSTOMER_ID NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  PURCHASE_DESCRIPTION VARCHAR2(500 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_98 on table crl_dept_po ... 
ALTER TABLE crl_dept_po
ADD CONSTRAINT PRIMARY_98 PRIMARY KEY
(
  PURCHASE_ORDER_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index PURCHASE_ORDER_FKIndex1 on crl_dept_po ...
CREATE INDEX PURCHASE_ORDER_FKIndex1 ON crl_dept_po
(
  CUSTOMER_ID
) 
;

-- DROP TABLE crl_dept_po_det CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_po_det ...
CREATE TABLE crl_dept_po_det (
  PURCHASE_ORDER_ID VARCHAR2(20 CHAR) NOT NULL,
  PURCHASE_ORDER_DETAIL_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR),
  QUANTITY NUMBER(10,0),
  PRICE NUMBER(10,0),
  PURCHASE_STATUS NUMBER(10,0),
  TAX_ID NUMBER(10,0),
  PURCHASE_TYPE NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR) NOT NULL,
  NOTE VARCHAR2(200 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_99 on table crl_dept_po_det ... 
ALTER TABLE crl_dept_po_det
ADD CONSTRAINT PRIMARY_99 PRIMARY KEY
(
  PURCHASE_ORDER_ID,
  PURCHASE_ORDER_DETAIL_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index PURCHASE_ORDER_DETAIL_FKIndex1 on crl_dept_po_det ...
CREATE INDEX PURCHASE_ORDER_DETAIL_FKIndex1 ON crl_dept_po_det
(
  PURCHASE_ORDER_ID,
  DEPARTMENT_ID
) 
;
PROMPT Creating Index PURCHASE_ORDER_DETAIL_FKIndex2 on crl_dept_po_det ...
CREATE INDEX PURCHASE_ORDER_DETAIL_FKIndex2 ON crl_dept_po_det
(
  PRODUCT_ID
) 
;
PROMPT Creating Index PURCHASE_ORDER_DETAIL_FKIndex3 on crl_dept_po_det ...
CREATE INDEX PURCHASE_ORDER_DETAIL_FKIndex3 ON crl_dept_po_det
(
  TAX_ID
) 
;

-- DROP TABLE crl_dept_po_det_log CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_po_det_log ...
CREATE TABLE crl_dept_po_det_log (
  PURCHASE_ORDER_DETAIL_LOG_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PURCHASE_ORDER_DETAIL_ID NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_100 on table crl_dept_po_det_log ... 
ALTER TABLE crl_dept_po_det_log
ADD CONSTRAINT PRIMARY_100 PRIMARY KEY
(
  PURCHASE_ORDER_DETAIL_LOG_ID,
  DEPARTMENT_ID
)
ENABLE
;

-- DROP TABLE crl_dept_po_log CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_po_log ...
CREATE TABLE crl_dept_po_log (
  PURCHASE_ORDER_LOG_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PURCHASE_ORDER_ID VARCHAR2(20 CHAR) NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_101 on table crl_dept_po_log ... 
ALTER TABLE crl_dept_po_log
ADD CONSTRAINT PRIMARY_101 PRIMARY KEY
(
  PURCHASE_ORDER_LOG_ID,
  DEPARTMENT_ID
)
ENABLE
;

-- DROP TABLE crl_dept_po_promo CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_po_promo ...
CREATE TABLE crl_dept_po_promo (
  PURCHASE_ORDER_ID VARCHAR2(20 CHAR) NOT NULL,
  PURCHASE_ORDER_DETAIL_ID NUMBER(10,0) NOT NULL,
  ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  GIFT_DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_PROMOTION_ID NUMBER(10,0),
  GIFT_ID NUMBER(10,0),
  GIFT_PRODUCT_ID NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_102 on table crl_dept_po_promo ... 
ALTER TABLE crl_dept_po_promo
ADD CONSTRAINT PRIMARY_102 PRIMARY KEY
(
  PURCHASE_ORDER_ID,
  PURCHASE_ORDER_DETAIL_ID,
  ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index PURCHASE_ORDER_PROMOTION_FKI_4 on crl_dept_po_promo ...
CREATE INDEX PURCHASE_ORDER_PROMOTION_FKI_4 ON crl_dept_po_promo
(
  DEPARTMENT_PROMOTION_ID
) 
;
PROMPT Creating Index PURCHASE_ORDER_PROMOTION_FKI_3 on crl_dept_po_promo ...
CREATE INDEX PURCHASE_ORDER_PROMOTION_FKI_3 ON crl_dept_po_promo
(
  PURCHASE_ORDER_ID,
  PURCHASE_ORDER_DETAIL_ID,
  DEPARTMENT_ID
) 
;
PROMPT Creating Index PURCHASE_ORDER_PROMOTION_FKI_5 on crl_dept_po_promo ...
CREATE INDEX PURCHASE_ORDER_PROMOTION_FKI_5 ON crl_dept_po_promo
(
  GIFT_ID,
  GIFT_DEPARTMENT_ID
) 
;

-- DROP TABLE crl_dept_prmtn CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_prmtn ...
CREATE TABLE crl_dept_prmtn (
  DEPARTMENT_PROMOTION_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PROMOTION_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  START_DATE DATE,
  END_DATE DATE,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_103 on table crl_dept_prmtn ... 
ALTER TABLE crl_dept_prmtn
ADD CONSTRAINT PRIMARY_103 PRIMARY KEY
(
  DEPARTMENT_PROMOTION_ID
)
ENABLE
;
PROMPT Creating Index DEPARTMENT_PROMOTION_FKIndex1 on crl_dept_prmtn ...
CREATE INDEX DEPARTMENT_PROMOTION_FKIndex1 ON crl_dept_prmtn
(
  PROMOTION_ID
) 
;
PROMPT Creating Index DEPARTMENT_PROMOTION_FKIndex2 on crl_dept_prmtn ...
CREATE INDEX DEPARTMENT_PROMOTION_FKIndex2 ON crl_dept_prmtn
(
  PRODUCT_ID
) 
;

-- DROP TABLE crl_dept_ret CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_ret ...
CREATE TABLE crl_dept_ret (
  DEPARTMENT_RETURN_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR),
  DEPARTMENT_ID NUMBER(10,0),
  RETURN_STATUS NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_104 on table crl_dept_ret ... 
ALTER TABLE crl_dept_ret
ADD CONSTRAINT PRIMARY_104 PRIMARY KEY
(
  DEPARTMENT_RETURN_ID
)
ENABLE
;

-- DROP TABLE crl_dept_ret_cost CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_ret_cost ...
CREATE TABLE crl_dept_ret_cost (
  DEPARTMENT_RETURN_ID NUMBER(10,0) NOT NULL,
  COST_TYPE NUMBER(10,0) NOT NULL,
  COST NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_105 on table crl_dept_ret_cost ... 
ALTER TABLE crl_dept_ret_cost
ADD CONSTRAINT PRIMARY_105 PRIMARY KEY
(
  DEPARTMENT_RETURN_ID,
  COST_TYPE
)
ENABLE
;
PROMPT Creating Index DEPARTMENT_RETURN_COST_FKIndex on crl_dept_ret_cost ...
CREATE INDEX DEPARTMENT_RETURN_COST_FKIndex ON crl_dept_ret_cost
(
  DEPARTMENT_RETURN_ID
) 
;

-- DROP TABLE crl_dept_ret_det CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_ret_det ...
CREATE TABLE crl_dept_ret_det (
  DEPARTMENT_RETURN_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  QUANTITY NUMBER(10,0),
  DESCRIPTION CLOB,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_106 on table crl_dept_ret_det ... 
ALTER TABLE crl_dept_ret_det
ADD CONSTRAINT PRIMARY_106 PRIMARY KEY
(
  DEPARTMENT_RETURN_ID,
  PRODUCT_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index DEPARTMENT_RETURN_DETAIL_FKInd on crl_dept_ret_det ...
CREATE INDEX DEPARTMENT_RETURN_DETAIL_FKInd ON crl_dept_ret_det
(
  DEPARTMENT_RETURN_ID
) 
;

-- DROP TABLE crl_dept_ret_po CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_ret_po ...
CREATE TABLE crl_dept_ret_po (
  PURCHASE_ORDER_ID VARCHAR2(20 CHAR) NOT NULL,
  PURCHASE_ORDER_DETAIL_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  RETURN_DATE DATE,
  DESCRIPTION CLOB,
  QUANTITY NUMBER(10,0),
  CREATE_DATE DATE NOT NULL,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  NEXT_PURCHASE_ORDER_ID VARCHAR2(20 CHAR),
  PRODUCT_ID VARCHAR2(20 CHAR),
  PRICE NUMBER(10,0)
);


PROMPT Creating Primary Key Constraint PRIMARY_107 on table crl_dept_ret_po ... 
ALTER TABLE crl_dept_ret_po
ADD CONSTRAINT PRIMARY_107 PRIMARY KEY
(
  PURCHASE_ORDER_ID,
  PURCHASE_ORDER_DETAIL_ID,
  DEPARTMENT_ID,
  CREATE_DATE
)
ENABLE
;

-- DROP TABLE crl_dept_stk CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk ...
CREATE TABLE crl_dept_stk (
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  QUANTITY NUMBER(10,0),
  ON_STORE_PRICE NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  GOOD_QUANTITY NUMBER(10,0),
  ERROR_QUANTITY NUMBER(10,0),
  LOST_QUANTITY NUMBER(10,0),
  DAMAGE_QUANTITY NUMBER(10,0),
  UNCONFIRM_QUANTITY NUMBER(10,0),
  POSITION VARCHAR2(200 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_108 on table crl_dept_stk ... 
ALTER TABLE crl_dept_stk
ADD CONSTRAINT PRIMARY_108 PRIMARY KEY
(
  DEPARTMENT_ID,
  PRODUCT_ID
)
ENABLE
;
PROMPT Creating Index DEPARTMENT_STOCK_FKIndex1_3 on crl_dept_stk ...
CREATE INDEX DEPARTMENT_STOCK_FKIndex1_3 ON crl_dept_stk
(
  PRODUCT_ID
) 
;
PROMPT Creating Index Index_3_18 on crl_dept_stk ...
CREATE INDEX Index_3_18 ON crl_dept_stk
(
  DEPARTMENT_ID,
  PRODUCT_ID
) 
;
PROMPT Creating Index Index_4_19 on crl_dept_stk ...
CREATE INDEX Index_4_19 ON crl_dept_stk
(
  CREATE_DATE
) 
;

-- DROP TABLE crl_dept_stk_his CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk_his ...
CREATE TABLE crl_dept_stk_his (
  DEPARTMENT_STOCK_HISTORY_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR),
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  QUANTITY NUMBER(10,0),
  CREATE_ID VARCHAR2(50 CHAR),
  CREATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  EXCLUSIVE_KEY NUMBER(10,0) DEFAULT '1',
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  DESCRIPTION VARCHAR2(200 CHAR),
  GOOD_COUNT NUMBER(10,0) DEFAULT '0',
  ERROR_COUNT NUMBER(10,0) DEFAULT '0',
  DAMAGE_COUNT NUMBER(10,0) DEFAULT '0',
  LOST_COUNT NUMBER(10,0) DEFAULT '0',
  UNCONFIRM_COUNT NUMBER(10,0) DEFAULT '0',
  DEPARTMENT_ID NUMBER(10,0) NOT NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_109 on table crl_dept_stk_his ... 
ALTER TABLE crl_dept_stk_his
ADD CONSTRAINT PRIMARY_109 PRIMARY KEY
(
  DEPARTMENT_STOCK_HISTORY_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index Index_3_17 on crl_dept_stk_his ...
CREATE INDEX Index_3_17 ON crl_dept_stk_his
(
  CREATE_DATE
) 
;
PROMPT Creating Index FK_department_stock_defect_1 on crl_dept_stk_his ...
CREATE INDEX FK_department_stock_defect_1 ON crl_dept_stk_his
(
  PRODUCT_ID,
  CREATE_DATE,
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_dept_stk_in_cst CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk_in_cst ...
CREATE TABLE crl_dept_stk_in_cst (
  STOCK_IN_ID VARCHAR2(15 CHAR) NOT NULL,
  COST_TYPE NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  COST NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_111 on table crl_dept_stk_in_cst ... 
ALTER TABLE crl_dept_stk_in_cst
ADD CONSTRAINT PRIMARY_111 PRIMARY KEY
(
  STOCK_IN_ID,
  COST_TYPE,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index DEPARTMENT_STOCK_IN_COST_FKInd on crl_dept_stk_in_cst ...
CREATE INDEX DEPARTMENT_STOCK_IN_COST_FKInd ON crl_dept_stk_in_cst
(
  STOCK_IN_ID,
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_dept_stk_in_det CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk_in_det ...
CREATE TABLE crl_dept_stk_in_det (
  STOCK_IN_ID VARCHAR2(15 CHAR) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  QUANTITY NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  PRICE NUMBER(10,0),
  ON_STORE_PRICE NUMBER(10,0),
  SOLD NUMBER(10,0) DEFAULT '0'
);


PROMPT Creating Primary Key Constraint PRIMARY_112 on table crl_dept_stk_in_det ... 
ALTER TABLE crl_dept_stk_in_det
ADD CONSTRAINT PRIMARY_112 PRIMARY KEY
(
  STOCK_IN_ID,
  PRODUCT_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index DEPARTMENT_STOCK_IN_DETAIL_F_4 on crl_dept_stk_in_det ...
CREATE INDEX DEPARTMENT_STOCK_IN_DETAIL_F_4 ON crl_dept_stk_in_det
(
  PRODUCT_ID
) 
;
PROMPT Creating Index DEPARTMENT_STOCK_IN_DETAIL_F_1 on crl_dept_stk_in_det ...
CREATE INDEX DEPARTMENT_STOCK_IN_DETAIL_F_1 ON crl_dept_stk_in_det
(
  STOCK_IN_ID,
  DEPARTMENT_ID
) 
;
PROMPT Creating Index Index_4_12 on crl_dept_stk_in_det ...
CREATE INDEX Index_4_12 ON crl_dept_stk_in_det
(
  PRODUCT_MASTER_ID
) 
;

-- DROP TABLE crl_dept_stk_in_his CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk_in_his ...
CREATE TABLE crl_dept_stk_in_his (
  STOCK_IN_ID VARCHAR2(15 CHAR) NOT NULL,
  SOURCE_DEPARTMENTID NUMBER(10,0) NOT NULL,
  STOCK_OUT_ID NUMBER(10,0) NOT NULL,
  DEST_DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  DESCRIPTION VARCHAR2(200 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_113 on table crl_dept_stk_in_his ... 
ALTER TABLE crl_dept_stk_in_his
ADD CONSTRAINT PRIMARY_113 PRIMARY KEY
(
  STOCK_IN_ID,
  STOCK_OUT_ID,
  SOURCE_DEPARTMENTID,
  DEST_DEPARTMENT_ID
)
ENABLE
;

-- DROP TABLE crl_dept_stk_out CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk_out ...
CREATE TABLE crl_dept_stk_out (
  STOCK_OUT_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  STOCK_OUT_DATE DATE,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  DESCRIPTION VARCHAR2(200 CHAR),
  DEFECT_STATUS_ID NUMBER(10,0),
  CONFIRM_FLG NUMBER(10,0) DEFAULT '0' NOT NULL,
  OTHER_DEPARTMENT_ID NUMBER(10,0) DEFAULT '0'
);


COMMENT ON COLUMN crl_dept_stk_out.CONFIRM_FLG IS 'Neu tra cho nha sx thi confirm flag = 1'
;

PROMPT Creating Primary Key Constraint PRIMARY_114 on table crl_dept_stk_out ... 
ALTER TABLE crl_dept_stk_out
ADD CONSTRAINT PRIMARY_114 PRIMARY KEY
(
  STOCK_OUT_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index Index_2_9 on crl_dept_stk_out ...
CREATE INDEX Index_2_9 ON crl_dept_stk_out
(
  STOCK_OUT_ID,
  DEPARTMENT_ID
) 
;
PROMPT Creating Index Index_3_15 on crl_dept_stk_out ...
CREATE INDEX Index_3_15 ON crl_dept_stk_out
(
  STOCK_OUT_ID
) 
;
PROMPT Creating Index Index_4_11 on crl_dept_stk_out ...
CREATE INDEX Index_4_11 ON crl_dept_stk_out
(
  DEPARTMENT_ID
) 
;
PROMPT Creating Index Index_5_6 on crl_dept_stk_out ...
CREATE INDEX Index_5_6 ON crl_dept_stk_out
(
  CREATE_DATE
) 
;

-- DROP TABLE crl_dept_stk_out_cst CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk_out_cst ...
CREATE TABLE crl_dept_stk_out_cst (
  STOCK_OUT_ID NUMBER(10,0) NOT NULL,
  COST_TYPE NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  COST NUMBER(10,0) NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_115 on table crl_dept_stk_out_cst ... 
ALTER TABLE crl_dept_stk_out_cst
ADD CONSTRAINT PRIMARY_115 PRIMARY KEY
(
  STOCK_OUT_ID,
  COST_TYPE,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index DEPARTMENT_STOCK_OUT_COST_FKIn on crl_dept_stk_out_cst ...
CREATE INDEX DEPARTMENT_STOCK_OUT_COST_FKIn ON crl_dept_stk_out_cst
(
  STOCK_OUT_ID,
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_dept_stk_out_det CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk_out_det ...
CREATE TABLE crl_dept_stk_out_det (
  STOCK_OUT_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  QUANTITY NUMBER(10,0),
  DESCRIPTION CLOB,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  DEFECT_STATUS_ID NUMBER(10,0),
  STOCK_OUT_DETAIL_ID NUMBER(10,0) DEFAULT '0' NOT NULL,
  GOOD_QUANTITY NUMBER(10,0) DEFAULT '0',
  ERROR_QUANTITY NUMBER(10,0) DEFAULT '0',
  DAMAGE_QUANTITY NUMBER(10,0) DEFAULT '0',
  LOST_QUANTITY NUMBER(10,0) DEFAULT '0',
  UNCONFIRM_QUANTITY NUMBER(10,0) DEFAULT '0'
);


PROMPT Creating Primary Key Constraint PRIMARY_116 on table crl_dept_stk_out_det ... 
ALTER TABLE crl_dept_stk_out_det
ADD CONSTRAINT PRIMARY_116 PRIMARY KEY
(
  STOCK_OUT_DETAIL_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index FK_department_stock_out_deta_3 on crl_dept_stk_out_det ...
CREATE INDEX FK_department_stock_out_deta_3 ON crl_dept_stk_out_det
(
  PRODUCT_ID
) 
;
PROMPT Creating Index FK_department_stock_out_deta_4 on crl_dept_stk_out_det ...
CREATE INDEX FK_department_stock_out_deta_4 ON crl_dept_stk_out_det
(
  STOCK_OUT_ID,
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_dept_stk_temp_valid CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk_temp_valid ...
CREATE TABLE crl_dept_stk_temp_valid (
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  QUANTITY NUMBER(10,0),
  ON_STORE_PRICE NUMBER(10,0),
  CREATE_DATE DATE NOT NULL,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0) DEFAULT '0',
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  GOOD_QUANTITY NUMBER(10,0) DEFAULT '0',
  ERROR_QUANTITY NUMBER(10,0) DEFAULT '0',
  LOST_QUANTITY NUMBER(10,0) DEFAULT '0',
  DAMAGE_QUANTITY NUMBER(10,0) DEFAULT '0',
  UNCONFIRM_QUANTITY NUMBER(10,0) DEFAULT '0',
  FIXED NUMBER(10,0) DEFAULT '0' NOT NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_117 on table crl_dept_stk_temp_valid ... 
ALTER TABLE crl_dept_stk_temp_valid
ADD CONSTRAINT PRIMARY_117 PRIMARY KEY
(
  DEPARTMENT_ID,
  PRODUCT_ID,
  CREATE_DATE
)
ENABLE
;
PROMPT Creating Index DEPARTMENT_STOCK_FKIndex1_8 on crl_dept_stk_temp_valid ...
CREATE INDEX DEPARTMENT_STOCK_FKIndex1_8 ON crl_dept_stk_temp_valid
(
  PRODUCT_ID
) 
;
PROMPT Creating Index Index_3_14 on crl_dept_stk_temp_valid ...
CREATE INDEX Index_3_14 ON crl_dept_stk_temp_valid
(
  DEPARTMENT_ID,
  PRODUCT_ID
) 
;
PROMPT Creating Index Index_4_10 on crl_dept_stk_temp_valid ...
CREATE INDEX Index_4_10 ON crl_dept_stk_temp_valid
(
  CREATE_DATE
) 
;
PROMPT Creating Index FK_department_stock_temp_2_5 on crl_dept_stk_temp_valid ...
CREATE INDEX FK_department_stock_temp_2_5 ON crl_dept_stk_temp_valid
(
  PRODUCT_MASTER_ID
) 
;

-- DROP TABLE crl_dept_stk_temp_valid_save CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_stk_temp_valid_save ...
CREATE TABLE crl_dept_stk_temp_valid_save (
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  QUANTITY NUMBER(10,0),
  ON_STORE_PRICE NUMBER(10,0),
  CREATE_DATE DATE NOT NULL,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  GOOD_QUANTITY NUMBER(10,0),
  ERROR_QUANTITY NUMBER(10,0),
  LOST_QUANTITY NUMBER(10,0),
  DAMAGE_QUANTITY NUMBER(10,0),
  UNCONFIRM_QUANTITY NUMBER(10,0),
  FIXED NUMBER(10,0) DEFAULT '0' NOT NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_118 on table crl_dept_stk_temp_valid_save ... 
ALTER TABLE crl_dept_stk_temp_valid_save
ADD CONSTRAINT PRIMARY_118 PRIMARY KEY
(
  DEPARTMENT_ID,
  PRODUCT_ID,
  CREATE_DATE
)
ENABLE
;
PROMPT Creating Index Index_3_13 on crl_dept_stk_temp_valid_save ...
CREATE INDEX Index_3_13 ON crl_dept_stk_temp_valid_save
(
  DEPARTMENT_ID,
  PRODUCT_ID
) 
;
PROMPT Creating Index DEPARTMENT_STOCK_FKIndex1_7 on crl_dept_stk_temp_valid_save ...
CREATE INDEX DEPARTMENT_STOCK_FKIndex1_7 ON crl_dept_stk_temp_valid_save
(
  PRODUCT_ID
) 
;
PROMPT Creating Index Index_4_9 on crl_dept_stk_temp_valid_save ...
CREATE INDEX Index_4_9 ON crl_dept_stk_temp_valid_save
(
  CREATE_DATE
) 
;
PROMPT Creating Index FK_department_stock_temp_2_4 on crl_dept_stk_temp_valid_save ...
CREATE INDEX FK_department_stock_temp_2_4 ON crl_dept_stk_temp_valid_save
(
  PRODUCT_MASTER_ID
) 
;

-- DROP TABLE crl_dept_timeline CASCADE CONSTRAINTS;


PROMPT Creating Table crl_dept_timeline ...
CREATE TABLE crl_dept_timeline (
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PERIOD NUMBER(10,0) DEFAULT '1' NOT NULL,
  START_TIME DATE,
  END_TIME DATE,
  WORKING_DAY DATE NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(45 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(45 CHAR),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_119 on table crl_dept_timeline ... 
ALTER TABLE crl_dept_timeline
ADD CONSTRAINT PRIMARY_119 PRIMARY KEY
(
  DEPARTMENT_ID,
  PERIOD
)
ENABLE
;

-- DROP TABLE crl_distbtor CASCADE CONSTRAINTS;


PROMPT Creating Table crl_distbtor ...
CREATE TABLE crl_distbtor (
  DISTRIBUTOR_ID NUMBER(10,0) NOT NULL,
  DISTRIBUTOR_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_120 on table crl_distbtor ... 
ALTER TABLE crl_distbtor
ADD CONSTRAINT PRIMARY_120 PRIMARY KEY
(
  DISTRIBUTOR_ID
)
ENABLE
;

-- DROP TABLE crl_emp CASCADE CONSTRAINTS;


PROMPT Creating Table crl_emp ...
CREATE TABLE crl_emp (
  EMPLOYEE_ID VARCHAR2(20 CHAR) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  START_DATE DATE,
  END_DATE DATE
);


PROMPT Creating Primary Key Constraint PRIMARY_121 on table crl_emp ... 
ALTER TABLE crl_emp
ADD CONSTRAINT PRIMARY_121 PRIMARY KEY
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index EMPLOYEE_FKIndex1 on crl_emp ...
CREATE INDEX EMPLOYEE_FKIndex1 ON crl_emp
(
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_emp_dayoff CASCADE CONSTRAINTS;


PROMPT Creating Table crl_emp_dayoff ...
CREATE TABLE crl_emp_dayoff (
  EMPLOYEE_ID VARCHAR2(20 CHAR) NOT NULL,
  DAYOFF_TIME DATE NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_122 on table crl_emp_dayoff ... 
ALTER TABLE crl_emp_dayoff
ADD CONSTRAINT PRIMARY_122 PRIMARY KEY
(
  EMPLOYEE_ID,
  DAYOFF_TIME,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index EMPLOYEE_DAYOFF_FKIndex1 on crl_emp_dayoff ...
CREATE INDEX EMPLOYEE_DAYOFF_FKIndex1 ON crl_emp_dayoff
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_emp_info CASCADE CONSTRAINTS;


PROMPT Creating Table crl_emp_info ...
CREATE TABLE crl_emp_info (
  EMPLOYEE_ID VARCHAR2(20 CHAR) NOT NULL,
  EMPLOYEE_NAME VARCHAR2(500 CHAR),
  ADDRESS VARCHAR2(500 CHAR),
  BIRTHDAY DATE,
  CONTRACT_ID NUMBER(10,0),
  SALARY NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  MANAGER VARCHAR2(20 CHAR) DEFAULT '0',
  BARCODE VARCHAR2(10 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_123 on table crl_emp_info ... 
ALTER TABLE crl_emp_info
ADD CONSTRAINT PRIMARY_123 PRIMARY KEY
(
  EMPLOYEE_ID
)
ENABLE
;

-- DROP TABLE crl_emp_money CASCADE CONSTRAINTS;


PROMPT Creating Table crl_emp_money ...
CREATE TABLE crl_emp_money (
  EMPLOYEE_ID VARCHAR2(20 CHAR) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  DATE_LOGIN DATE,
  DATE_LOGOUT DATE,
  WORKING_DAY VARCHAR2(45 CHAR) NOT NULL,
  IN_MONEY NUMBER(10,0) DEFAULT '0',
  OUT_MONEY NUMBER(10,0) DEFAULT '0',
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_124 on table crl_emp_money ... 
ALTER TABLE crl_emp_money
ADD CONSTRAINT PRIMARY_124 PRIMARY KEY
(
  EMPLOYEE_ID,
  DEPARTMENT_ID,
  WORKING_DAY
)
ENABLE
;

-- DROP TABLE crl_emp_reward CASCADE CONSTRAINTS;


PROMPT Creating Table crl_emp_reward ...
CREATE TABLE crl_emp_reward (
  EMPLOYEE_ID VARCHAR2(20 CHAR) NOT NULL,
  REWARD_DATE DATE NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  REWARD_VALUE NUMBER(10,0),
  REWARD_NAME VARCHAR2(500 CHAR),
  MONEY_VALUE NUMBER(10,0),
  GIFT_ID NUMBER(10,0),
  GIFT_PRODUCT_ID NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_125 on table crl_emp_reward ... 
ALTER TABLE crl_emp_reward
ADD CONSTRAINT PRIMARY_125 PRIMARY KEY
(
  EMPLOYEE_ID,
  REWARD_DATE,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index EMPLOYEE_REWARD_FKIndex1 on crl_emp_reward ...
CREATE INDEX EMPLOYEE_REWARD_FKIndex1 ON crl_emp_reward
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_emp_wrkg_days CASCADE CONSTRAINTS;


PROMPT Creating Table crl_emp_wrkg_days ...
CREATE TABLE crl_emp_wrkg_days (
  EMPLOYEE_ID VARCHAR2(20 CHAR) NOT NULL,
  WORKING_DAY DATE NOT NULL,
  PERIOD NUMBER(10,0),
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  START_TIME DATE,
  END_TIME DATE
);


PROMPT Creating Primary Key Constraint PRIMARY_126 on table crl_emp_wrkg_days ... 
ALTER TABLE crl_emp_wrkg_days
ADD CONSTRAINT PRIMARY_126 PRIMARY KEY
(
  EMPLOYEE_ID,
  WORKING_DAY
)
ENABLE
;
PROMPT Creating Index EMPLOYEE_WORKING_DAYS_FKIndex1 on crl_emp_wrkg_days ...
CREATE INDEX EMPLOYEE_WORKING_DAYS_FKIndex1 ON crl_emp_wrkg_days
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_ex_prd_size CASCADE CONSTRAINTS;


PROMPT Creating Table crl_ex_prd_size ...
CREATE TABLE crl_ex_prd_size (
  SIZE_ID NUMBER(10,0) NOT NULL,
  SIZE_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_128 on table crl_ex_prd_size ... 
ALTER TABLE crl_ex_prd_size
ADD CONSTRAINT PRIMARY_128 PRIMARY KEY
(
  SIZE_ID
)
ENABLE
;

-- DROP TABLE crl_gift CASCADE CONSTRAINTS;


PROMPT Creating Table crl_gift ...
CREATE TABLE crl_gift (
  GIFT_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  GIFT_NAME VARCHAR2(500 CHAR),
  QUANTITY NUMBER(10,0),
  SUPPLIER_ID NUMBER(10,0),
  PRICE NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_129 on table crl_gift ... 
ALTER TABLE crl_gift
ADD CONSTRAINT PRIMARY_129 PRIMARY KEY
(
  GIFT_ID,
  DEPARTMENT_ID
)
ENABLE
;

-- DROP TABLE crl_mn_price CASCADE CONSTRAINTS;


PROMPT Creating Table crl_mn_price ...
CREATE TABLE crl_mn_price (
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR) NOT NULL,
  PRICE NUMBER(10,0) DEFAULT '0' NOT NULL,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  WHOLE_SALE_PRICE NUMBER(10,0) DEFAULT '0'
);


PROMPT Creating Primary Key Constraint PRIMARY_130 on table crl_mn_price ... 
ALTER TABLE crl_mn_price
ADD CONSTRAINT PRIMARY_130 PRIMARY KEY
(
  DEPARTMENT_ID,
  PRODUCT_MASTER_ID
)
ENABLE
;

-- DROP TABLE crl_mn_stk CASCADE CONSTRAINTS;


PROMPT Creating Table crl_mn_stk ...
CREATE TABLE crl_mn_stk (
  STOCK_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  QUANTITY NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  GOOD_QUANTITY NUMBER(10,0) DEFAULT '0',
  ERROR_QUANTITY NUMBER(10,0) DEFAULT '0',
  DAMAGE_QUANTITY NUMBER(10,0) DEFAULT '0',
  LOST_QUANTITY NUMBER(10,0) DEFAULT '0',
  UNCONFIRM_QUANTITY NUMBER(10,0) DEFAULT '0',
  POSITION VARCHAR2(200 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_131 on table crl_mn_stk ... 
ALTER TABLE crl_mn_stk
ADD CONSTRAINT PRIMARY_131 PRIMARY KEY
(
  STOCK_ID
)
ENABLE
;
PROMPT Creating Index STOCK_FKIndex1 on crl_mn_stk ...
CREATE INDEX STOCK_FKIndex1 ON crl_mn_stk
(
  PRODUCT_ID
) 
;
PROMPT Creating Index Index_3_11 on crl_mn_stk ...
CREATE INDEX Index_3_11 ON crl_mn_stk
(
  PRODUCT_MASTER_ID
) 
;
PROMPT Creating Index Index_4_8 on crl_mn_stk ...
CREATE INDEX Index_4_8 ON crl_mn_stk
(
  PRODUCT_MASTER_ID,
  PRODUCT_ID
) 
;

-- DROP TABLE crl_mn_stk_his CASCADE CONSTRAINTS;


PROMPT Creating Table crl_mn_stk_his ...
CREATE TABLE crl_mn_stk_his (
  STOCK_HISTORY_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR) NOT NULL,
  QUANTITY NUMBER(10,0) NOT NULL,
  CREATE_ID VARCHAR2(50 CHAR),
  CREATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  EXCLUSIVE_KEY NUMBER(10,0) DEFAULT '1',
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  STOCK_ID NUMBER(10,0) NOT NULL,
  DESCRIPTION VARCHAR2(200 CHAR),
  GOOD_COUNT NUMBER(10,0) DEFAULT '0',
  ERROR_COUNT NUMBER(10,0) DEFAULT '0',
  DAMAGE_COUNT NUMBER(10,0) DEFAULT '0',
  LOST_COUNT NUMBER(10,0) DEFAULT '0',
  UNCONFIRM_COUNT NUMBER(10,0) DEFAULT '0'
);


PROMPT Creating Primary Key Constraint PRIMARY_132 on table crl_mn_stk_his ... 
ALTER TABLE crl_mn_stk_his
ADD CONSTRAINT PRIMARY_132 PRIMARY KEY
(
  STOCK_HISTORY_ID
)
ENABLE
;
PROMPT Creating Index FK_stock_defect_4 on crl_mn_stk_his ...
CREATE INDEX FK_stock_defect_4 ON crl_mn_stk_his
(
  STOCK_ID
) 
;
PROMPT Creating Index FK_stock_defect_1 on crl_mn_stk_his ...
CREATE INDEX FK_stock_defect_1 ON crl_mn_stk_his
(
  PRODUCT_ID
) 
;
PROMPT Creating Index FK_stock_defect_2 on crl_mn_stk_his ...
CREATE INDEX FK_stock_defect_2 ON crl_mn_stk_his
(
  PRODUCT_MASTER_ID
) 
;

-- DROP TABLE crl_mnftr CASCADE CONSTRAINTS;


PROMPT Creating Table crl_mnftr ...
CREATE TABLE crl_mnftr (
  MANUFACTURER_ID NUMBER(10,0) NOT NULL,
  MANUFACTURER_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_133 on table crl_mnftr ... 
ALTER TABLE crl_mnftr
ADD CONSTRAINT PRIMARY_133 PRIMARY KEY
(
  MANUFACTURER_ID
)
ENABLE
;

-- DROP TABLE crl_other_trans_log CASCADE CONSTRAINTS;


PROMPT Creating Table crl_other_trans_log ...
CREATE TABLE crl_other_trans_log (
  TRANSACTION_DATE DATE NOT NULL,
  TABLE_NAME NUMBER(10,0) NOT NULL,
  FIELD_NAME NUMBER(10,0),
  ACTION VARCHAR2(500 CHAR),
  VALUE_BEFORE VARCHAR2(500 CHAR),
  VALUE_AFTER VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_134 on table crl_other_trans_log ... 
ALTER TABLE crl_other_trans_log
ADD CONSTRAINT PRIMARY_134 PRIMARY KEY
(
  TRANSACTION_DATE
)
ENABLE
;

-- DROP TABLE crl_pblsh_cpn CASCADE CONSTRAINTS;


PROMPT Creating Table crl_pblsh_cpn ...
CREATE TABLE crl_pblsh_cpn (
  COUPON_ID NUMBER(10,0) NOT NULL,
  PUBLISHED_COUPON_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  START_DATE DATE,
  END_DATE DATE,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_135 on table crl_pblsh_cpn ... 
ALTER TABLE crl_pblsh_cpn
ADD CONSTRAINT PRIMARY_135 PRIMARY KEY
(
  COUPON_ID,
  PUBLISHED_COUPON_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index PUBLISHED_COUPON_FKIndex1 on crl_pblsh_cpn ...
CREATE INDEX PUBLISHED_COUPON_FKIndex1 ON crl_pblsh_cpn
(
  COUPON_ID
) 
;

-- DROP TABLE crl_pkgr CASCADE CONSTRAINTS;


PROMPT Creating Table crl_pkgr ...
CREATE TABLE crl_pkgr (
  PACKAGER_ID NUMBER(10,0) NOT NULL,
  PACKAGER_NAME VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_136 on table crl_pkgr ... 
ALTER TABLE crl_pkgr
ADD CONSTRAINT PRIMARY_136 PRIMARY KEY
(
  PACKAGER_ID
)
ENABLE
;

-- DROP TABLE crl_pos_log CASCADE CONSTRAINTS;


PROMPT Creating Table crl_pos_log ...
CREATE TABLE crl_pos_log (
  Id NUMBER(24,0) NOT NULL,
  Date_ DATE NOT NULL,
  Thread VARCHAR2(255 CHAR) NOT NULL,
  Level_ VARCHAR2(50 CHAR) NOT NULL,
  Logger VARCHAR2(255 CHAR) NOT NULL,
  Message CLOB NOT NULL,
  Exception VARCHAR2(2000 CHAR),
  Pos_User VARCHAR2(100 CHAR),
  Pos_Action VARCHAR2(100 CHAR)
);


COMMENT ON COLUMN crl_pos_log.Date_ IS 'ORIGINAL NAME:Date'
;

COMMENT ON COLUMN crl_pos_log.Level_ IS 'ORIGINAL NAME:Level'
;

PROMPT Creating Primary Key Constraint PRIMARY_137 on table crl_pos_log ... 
ALTER TABLE crl_pos_log
ADD CONSTRAINT PRIMARY_137 PRIMARY KEY
(
  Id
)
ENABLE
;

-- DROP TABLE crl_pos_trans CASCADE CONSTRAINTS;


PROMPT Creating Table crl_pos_trans ...
CREATE TABLE crl_pos_trans (
  POS_Transaction_Id VARCHAR2(10 CHAR) NOT NULL,
  Transaction_Id VARCHAR2(12 CHAR) NOT NULL,
  Store_Id VARCHAR2(5 CHAR) NOT NULL,
  Register_Id VARCHAR2(2 CHAR) NOT NULL,
  Cashier_Id VARCHAR2(6 CHAR) NOT NULL,
  Amount_In FLOAT,
  Amount_Out FLOAT,
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  DEL_FLG NUMBER(10,0) DEFAULT '0'
);


PROMPT Creating Primary Key Constraint PRIMARY_138 on table crl_pos_trans ... 
ALTER TABLE crl_pos_trans
ADD CONSTRAINT PRIMARY_138 PRIMARY KEY
(
  POS_Transaction_Id
)
ENABLE
;

-- DROP TABLE crl_prd CASCADE CONSTRAINTS;


PROMPT Creating Table crl_prd ...
CREATE TABLE crl_prd (
  PRODUCT_ID VARCHAR2(20 CHAR) NOT NULL,
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  BLOCK_ID NUMBER(10,0),
  BLOCK_DETAIL_ID VARCHAR2(10 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  QUANTITY NUMBER(10,0),
  PRICE NUMBER(10,0),
  TAX_ID NUMBER(10,0),
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  BARCODE VARCHAR2(20 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_139 on table crl_prd ... 
ALTER TABLE crl_prd
ADD CONSTRAINT PRIMARY_139 PRIMARY KEY
(
  PRODUCT_ID
)
ENABLE
;
PROMPT Creating Index product_size on crl_prd ...
CREATE INDEX product_size ON crl_prd
(
  EX_FLD2
) 
;
PROMPT Creating Index PRODUCT_FKIndex1 on crl_prd ...
CREATE INDEX PRODUCT_FKIndex1 ON crl_prd
(
  PRODUCT_MASTER_ID
) 
;
PROMPT Creating Index PRODUCT_FKIndex2 on crl_prd ...
CREATE INDEX PRODUCT_FKIndex2 ON crl_prd
(
  BLOCK_ID,
  BLOCK_DETAIL_ID
) 
;
PROMPT Creating Index product_color on crl_prd ...
CREATE INDEX product_color ON crl_prd
(
  EX_FLD1
) 
;

-- DROP TABLE crl_prd_mst CASCADE CONSTRAINTS;


PROMPT Creating Table crl_prd_mst ...
CREATE TABLE crl_prd_mst (
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR) NOT NULL,
  PRODUCT_NAME VARCHAR2(500 CHAR),
  DESCRIPTION CLOB,
  IMAGE_PATH VARCHAR2(500 CHAR),
  CATEGORY_ID NUMBER(10,0),
  COUNTRY_ID NUMBER(10,0),
  UNIT_ID NUMBER(10,0),
  TYPE_ID NUMBER(10,0),
  MANUFACTURER_ID NUMBER(10,0),
  SUPPLIER_ID NUMBER(10,0),
  PACKAGER_ID NUMBER(10,0),
  DISTRIBUTOR_ID NUMBER(10,0),
  BARCODE VARCHAR2(13 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0) DEFAULT '0',
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_140 on table crl_prd_mst ... 
ALTER TABLE crl_prd_mst
ADD CONSTRAINT PRIMARY_140 PRIMARY KEY
(
  PRODUCT_MASTER_ID
)
ENABLE
;
PROMPT Creating Index PRODUCT_MASTER_FKIndex8 on crl_prd_mst ...
CREATE INDEX PRODUCT_MASTER_FKIndex8 ON crl_prd_mst
(
  COUNTRY_ID
) 
;
PROMPT Creating Index PRODUCT_MASTER_FKIndex1 on crl_prd_mst ...
CREATE INDEX PRODUCT_MASTER_FKIndex1 ON crl_prd_mst
(
  CATEGORY_ID
) 
;
PROMPT Creating Index PRODUCT_MASTER_FKIndex2 on crl_prd_mst ...
CREATE INDEX PRODUCT_MASTER_FKIndex2 ON crl_prd_mst
(
  TYPE_ID
) 
;
PROMPT Creating Index PRODUCT_MASTER_FKIndex5 on crl_prd_mst ...
CREATE INDEX PRODUCT_MASTER_FKIndex5 ON crl_prd_mst
(
  MANUFACTURER_ID
) 
;
PROMPT Creating Index PRODUCT_MASTER_FKIndex6 on crl_prd_mst ...
CREATE INDEX PRODUCT_MASTER_FKIndex6 ON crl_prd_mst
(
  PACKAGER_ID
) 
;
PROMPT Creating Index PRODUCT_MASTER_FKIndex7 on crl_prd_mst ...
CREATE INDEX PRODUCT_MASTER_FKIndex7 ON crl_prd_mst
(
  DISTRIBUTOR_ID
) 
;

-- DROP TABLE crl_prd_unit CASCADE CONSTRAINTS;


PROMPT Creating Table crl_prd_unit ...
CREATE TABLE crl_prd_unit (
  UNIT_ID NUMBER(10,0) NOT NULL,
  UNIT_NAME VARCHAR2(30 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(20 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(20 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0) DEFAULT '0',
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_142 on table crl_prd_unit ... 
ALTER TABLE crl_prd_unit
ADD CONSTRAINT PRIMARY_142 PRIMARY KEY
(
  UNIT_ID
)
ENABLE
;

-- DROP TABLE crl_promo CASCADE CONSTRAINTS;


PROMPT Creating Table crl_promo ...
CREATE TABLE crl_promo (
  PROMOTION_ID NUMBER(10,0) NOT NULL,
  PROMOTION_NAME VARCHAR2(500 CHAR),
  DISCOUNT_PRICE NUMBER(10,0),
  DISCOUNT_PERCENT NUMBER(10,0),
  PROMOTION_TYPE NUMBER(10,0),
  GIFT_PRODUCT_ID NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_143 on table crl_promo ... 
ALTER TABLE crl_promo
ADD CONSTRAINT PRIMARY_143 PRIMARY KEY
(
  PROMOTION_ID
)
ENABLE
;

-- DROP TABLE crl_reicpt CASCADE CONSTRAINTS;


PROMPT Creating Table crl_reicpt ...
CREATE TABLE crl_reicpt (
  RECEIPT_ID VARCHAR2(20 CHAR) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  PURCHASE_ORDER_ID VARCHAR2(20 CHAR) NOT NULL,
  RECEIPT_NAME VARCHAR2(500 CHAR),
  RECEIPT_NUMBER VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_144 on table crl_reicpt ... 
ALTER TABLE crl_reicpt
ADD CONSTRAINT PRIMARY_144 PRIMARY KEY
(
  RECEIPT_ID,
  DEPARTMENT_ID
)
ENABLE
;
PROMPT Creating Index RECEIPT_FKIndex1 on crl_reicpt ...
CREATE INDEX RECEIPT_FKIndex1 ON crl_reicpt
(
  PURCHASE_ORDER_ID,
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_reicpt_out CASCADE CONSTRAINTS;


PROMPT Creating Table crl_reicpt_out ...
CREATE TABLE crl_reicpt_out (
  RECEIPT_OUT_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  RECEIPT_OUT_NAME NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_145 on table crl_reicpt_out ... 
ALTER TABLE crl_reicpt_out
ADD CONSTRAINT PRIMARY_145 PRIMARY KEY
(
  RECEIPT_OUT_ID,
  DEPARTMENT_ID
)
ENABLE
;

-- DROP TABLE crl_reicpt_out_cst CASCADE CONSTRAINTS;


PROMPT Creating Table crl_reicpt_out_cst ...
CREATE TABLE crl_reicpt_out_cst (
  RECEIPT_OUT_ID NUMBER(10,0) NOT NULL,
  DEPARTMENT_ID NUMBER(10,0) NOT NULL,
  COST_TYPE NUMBER(10,0) NOT NULL,
  COST NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_146 on table crl_reicpt_out_cst ... 
ALTER TABLE crl_reicpt_out_cst
ADD CONSTRAINT PRIMARY_146 PRIMARY KEY
(
  RECEIPT_OUT_ID,
  DEPARTMENT_ID,
  COST_TYPE
)
ENABLE
;
PROMPT Creating Index RECEIPT_OUT_COST_FKIndex1 on crl_reicpt_out_cst ...
CREATE INDEX RECEIPT_OUT_COST_FKIndex1 ON crl_reicpt_out_cst
(
  RECEIPT_OUT_ID,
  DEPARTMENT_ID
) 
;

-- DROP TABLE crl_ret_blk_in CASCADE CONSTRAINTS;


PROMPT Creating Table crl_ret_blk_in ...
CREATE TABLE crl_ret_blk_in (
  BLOCK_IN_ID NUMBER(10,0) NOT NULL,
  BLOCK_DETAIL_ID NUMBER(10,0) NOT NULL,
  DESCRIPTION VARCHAR2(500 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_147 on table crl_ret_blk_in ... 
ALTER TABLE crl_ret_blk_in
ADD CONSTRAINT PRIMARY_147 PRIMARY KEY
(
  BLOCK_IN_ID,
  BLOCK_DETAIL_ID
)
ENABLE
;

-- DROP TABLE crl_ret_prd CASCADE CONSTRAINTS;


PROMPT Creating Table crl_ret_prd ...
CREATE TABLE crl_ret_prd (
  RETURN_PRODUCT_ID NUMBER(10,0) NOT NULL,
  PRODUCT_ID VARCHAR2(20 CHAR),
  PRODUCT_MASTER_ID VARCHAR2(13 CHAR),
  DESCRIPTION NUMBER(10,0),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR),
  QUANTITY NUMBER(10,0)
);


PROMPT Creating Primary Key Constraint PRIMARY_148 on table crl_ret_prd ... 
ALTER TABLE crl_ret_prd
ADD CONSTRAINT PRIMARY_148 PRIMARY KEY
(
  RETURN_PRODUCT_ID
)
ENABLE
;

-- DROP TABLE crl_ret_trans CASCADE CONSTRAINTS;


PROMPT Creating Table crl_ret_trans ...
CREATE TABLE crl_ret_trans (
  Return_Transaction_Id VARCHAR2(15 CHAR) NOT NULL,
  Transaction_Id VARCHAR2(12 CHAR) NOT NULL,
  POS_Transaction_Id VARCHAR2(10 CHAR) NOT NULL,
  Store_Id VARCHAR2(5 CHAR) NOT NULL,
  Register_Id VARCHAR2(2 CHAR) NOT NULL,
  Cashier_Id VARCHAR2(6 CHAR) NOT NULL,
  Customer_Id VARCHAR2(15 CHAR),
  Purchase_Order_Id VARCHAR2(15 CHAR),
  Return_Id VARCHAR2(15 CHAR),
  CREATE_DATE DATE,
  CREATE_ID VARCHAR2(50 CHAR),
  UPDATE_DATE DATE,
  UPDATE_ID VARCHAR2(50 CHAR),
  EXCLUSIVE_KEY NUMBER(10,0),
  DEL_FLG NUMBER(10,0) DEFAULT '0',
  EX_FLD1 NUMBER(10,0),
  EX_FLD2 NUMBER(10,0),
  EX_FLD3 NUMBER(10,0),
  EX_FLD4 VARCHAR2(45 CHAR),
  EX_FLD5 VARCHAR2(45 CHAR)
);


PROMPT Creating Primary Key Constraint PRIMARY_149 on table crl_ret_trans ... 
ALTER TABLE crl_ret_trans
ADD CONSTRAINT PRIMARY_149 PRIMARY KEY
(
  Return_Transaction_Id
)
ENABLE
;

connect pos2/pos2;

PROMPT Creating Foreign Key Constraint crl_contract_ibfk_1 on table crl_emp...
ALTER TABLE crl_contract
ADD CONSTRAINT crl_contract_ibfk_1 FOREIGN KEY
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
)
REFERENCES crl_emp
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_coupon_ibfk_1 on table crl_coupon_typ...
ALTER TABLE crl_coupon
ADD CONSTRAINT crl_coupon_ibfk_1 FOREIGN KEY
(
  COUPON_TYPE
)
REFERENCES crl_coupon_typ
(
  COUPON_TYPE_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_cust_det_ibfk_1 on table crl_cust...
ALTER TABLE crl_cust_det
ADD CONSTRAINT crl_cust_det_ibfk_1 FOREIGN KEY
(
  CUSTOMER_ID
)
REFERENCES crl_cust
(
  CUSTOMER_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_cost_ibfk_1 on table crl_dept...
ALTER TABLE crl_dept_cost
ADD CONSTRAINT crl_dept_cost_ibfk_1 FOREIGN KEY
(
  DEPARTMENT_ID
)
REFERENCES crl_dept
(
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint fk_crl_dept_mng_crl_dept1 on table crl_dept...
ALTER TABLE crl_dept_mng
ADD CONSTRAINT fk_crl_dept_mng_crl_dept1 FOREIGN KEY
(
  DEPARTMENT_ID
)
REFERENCES crl_dept
(
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint fk_crl_dept_mng_crl_emp_info1 on table crl_emp_info...
ALTER TABLE crl_dept_mng
ADD CONSTRAINT fk_crl_dept_mng_crl_emp_info1 FOREIGN KEY
(
  EMPLOYEE_ID
)
REFERENCES crl_emp_info
(
  EMPLOYEE_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_po_ibfk_1 on table crl_cust...
ALTER TABLE crl_dept_po
ADD CONSTRAINT crl_dept_po_ibfk_1 FOREIGN KEY
(
  CUSTOMER_ID
)
REFERENCES crl_cust
(
  CUSTOMER_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_po_det_ibfk_2 on table crl_prd...
ALTER TABLE crl_dept_po_det
ADD CONSTRAINT crl_dept_po_det_ibfk_2 FOREIGN KEY
(
  PRODUCT_ID
)
REFERENCES crl_prd
(
  PRODUCT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_po_promo_ibfk_1 on table crl_dept_po_det...
ALTER TABLE crl_dept_po_promo
ADD CONSTRAINT crl_dept_po_promo_ibfk_1 FOREIGN KEY
(
  PURCHASE_ORDER_ID,
  PURCHASE_ORDER_DETAIL_ID,
  DEPARTMENT_ID
)
REFERENCES crl_dept_po_det
(
  PURCHASE_ORDER_ID,
  PURCHASE_ORDER_DETAIL_ID,
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_po_promo_ibfk_2 on table crl_dept_prmtn...
ALTER TABLE crl_dept_po_promo
ADD CONSTRAINT crl_dept_po_promo_ibfk_2 FOREIGN KEY
(
  DEPARTMENT_PROMOTION_ID
)
REFERENCES crl_dept_prmtn
(
  DEPARTMENT_PROMOTION_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_po_promo_ibfk_3 on table crl_gift...
ALTER TABLE crl_dept_po_promo
ADD CONSTRAINT crl_dept_po_promo_ibfk_3 FOREIGN KEY
(
  GIFT_ID,
  GIFT_DEPARTMENT_ID
)
REFERENCES crl_gift
(
  GIFT_ID,
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_prmtn_ibfk_1 on table crl_promo...
ALTER TABLE crl_dept_prmtn
ADD CONSTRAINT crl_dept_prmtn_ibfk_1 FOREIGN KEY
(
  PROMOTION_ID
)
REFERENCES crl_promo
(
  PROMOTION_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_prmtn_ibfk_2 on table crl_prd...
ALTER TABLE crl_dept_prmtn
ADD CONSTRAINT crl_dept_prmtn_ibfk_2 FOREIGN KEY
(
  PRODUCT_ID
)
REFERENCES crl_prd
(
  PRODUCT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_ret_cost_ibfk_1 on table crl_dept_ret...
ALTER TABLE crl_dept_ret_cost
ADD CONSTRAINT crl_dept_ret_cost_ibfk_1 FOREIGN KEY
(
  DEPARTMENT_RETURN_ID
)
REFERENCES crl_dept_ret
(
  DEPARTMENT_RETURN_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_ret_det_ibfk_1 on table crl_dept_ret...
ALTER TABLE crl_dept_ret_det
ADD CONSTRAINT crl_dept_ret_det_ibfk_1 FOREIGN KEY
(
  DEPARTMENT_RETURN_ID
)
REFERENCES crl_dept_ret
(
  DEPARTMENT_RETURN_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_stk_ibfk_1 on table crl_prd...
ALTER TABLE crl_dept_stk
ADD CONSTRAINT crl_dept_stk_ibfk_1 FOREIGN KEY
(
  PRODUCT_ID
)
REFERENCES crl_prd
(
  PRODUCT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_stk_in_cst_ibfk_1 on table crl_dept_stk_in...
ALTER TABLE crl_dept_stk_in_cst
ADD CONSTRAINT crl_dept_stk_in_cst_ibfk_1 FOREIGN KEY
(
  STOCK_IN_ID,
  DEPARTMENT_ID
)
REFERENCES crl_dept_stk_in
(
  STOCK_IN_ID,
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_stk_in_det_ibfk_1 on table crl_dept_stk_in...
ALTER TABLE crl_dept_stk_in_det
ADD CONSTRAINT crl_dept_stk_in_det_ibfk_1 FOREIGN KEY
(
  STOCK_IN_ID,
  DEPARTMENT_ID
)
REFERENCES crl_dept_stk_in
(
  STOCK_IN_ID,
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_stk_in_det_ibfk_2 on table crl_prd...
ALTER TABLE crl_dept_stk_in_det
ADD CONSTRAINT crl_dept_stk_in_det_ibfk_2 FOREIGN KEY
(
  PRODUCT_ID
)
REFERENCES crl_prd
(
  PRODUCT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_stk_out_cst_ibfk_1 on table crl_dept_stk_out...
ALTER TABLE crl_dept_stk_out_cst
ADD CONSTRAINT crl_dept_stk_out_cst_ibfk_1 FOREIGN KEY
(
  STOCK_OUT_ID,
  DEPARTMENT_ID
)
REFERENCES crl_dept_stk_out
(
  STOCK_OUT_ID,
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_stk_temp_valid_ibfk_1 on table crl_prd...
ALTER TABLE crl_dept_stk_temp_valid
ADD CONSTRAINT crl_dept_stk_temp_valid_ibfk_1 FOREIGN KEY
(
  PRODUCT_ID
)
REFERENCES crl_prd
(
  PRODUCT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_dept_stk_temp_valid_save_i on table crl_prd...
ALTER TABLE crl_dept_stk_temp_valid_save
ADD CONSTRAINT crl_dept_stk_temp_valid_save_i FOREIGN KEY
(
  PRODUCT_ID
)
REFERENCES crl_prd
(
  PRODUCT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_emp_dayoff_ibfk_1 on table crl_emp...
ALTER TABLE crl_emp_dayoff
ADD CONSTRAINT crl_emp_dayoff_ibfk_1 FOREIGN KEY
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
)
REFERENCES crl_emp
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_emp_reward_ibfk_1 on table crl_emp...
ALTER TABLE crl_emp_reward
ADD CONSTRAINT crl_emp_reward_ibfk_1 FOREIGN KEY
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
)
REFERENCES crl_emp
(
  EMPLOYEE_ID,
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_pblsh_cpn_ibfk_1 on table crl_coupon...
ALTER TABLE crl_pblsh_cpn
ADD CONSTRAINT crl_pblsh_cpn_ibfk_1 FOREIGN KEY
(
  COUPON_ID
)
REFERENCES crl_coupon
(
  COUPON_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint product_color on table crl_ex_prd_color...
ALTER TABLE crl_prd
ADD CONSTRAINT product_color FOREIGN KEY
(
  EX_FLD1
)
REFERENCES crl_ex_prd_color
(
  COLOR_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint product_size on table crl_ex_prd_size...
ALTER TABLE crl_prd
ADD CONSTRAINT product_size FOREIGN KEY
(
  EX_FLD2
)
REFERENCES crl_ex_prd_size
(
  SIZE_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_reicpt_ibfk_1 on table crl_dept_po...
ALTER TABLE crl_reicpt
ADD CONSTRAINT crl_reicpt_ibfk_1 FOREIGN KEY
(
  PURCHASE_ORDER_ID,
  DEPARTMENT_ID
)
REFERENCES crl_dept_po
(
  PURCHASE_ORDER_ID,
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_reicpt_out_cst_ibfk_1 on table crl_reicpt_out...
ALTER TABLE crl_reicpt_out_cst
ADD CONSTRAINT crl_reicpt_out_cst_ibfk_1 FOREIGN KEY
(
  RECEIPT_OUT_ID,
  DEPARTMENT_ID
)
REFERENCES crl_reicpt_out
(
  RECEIPT_OUT_ID,
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint crl_sche_tmplate_ibfk_1 on table crl_dept...
ALTER TABLE crl_sche_tmplate
ADD CONSTRAINT crl_sche_tmplate_ibfk_1 FOREIGN KEY
(
  DEPARTMENT_ID
)
REFERENCES crl_dept
(
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint fk_CRL_STK_OUT_CRL_DEPT1 on table crl_dept...
ALTER TABLE crl_stk_out
ADD CONSTRAINT fk_CRL_STK_OUT_CRL_DEPT1 FOREIGN KEY
(
  DEPARTMENT_ID
)
REFERENCES crl_dept
(
  DEPARTMENT_ID
)
ENABLE
;

PROMPT Creating Foreign Key Constraint FK_stock_out on table crl_stk_out...
ALTER TABLE crl_stk_out_det
ADD CONSTRAINT FK_stock_out FOREIGN KEY
(
  STOCKOUT_ID
)
REFERENCES crl_stk_out
(
  STOCKOUT_ID
)
ENABLE
;

CREATE OR REPLACE TRIGGER crl_pos_log_Id_TRG BEFORE INSERT OR UPDATE ON crl_pos_log
FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.Id IS NULL THEN
    SELECT  crl_pos_log_Id_SEQ.NEXTVAL INTO v_newVal FROM DUAL;
    -- If this is the first time this table have been inserted into (sequence == 1)
    IF v_newVal = 1 THEN 
      --get the max indentity value from the table
      SELECT NVL(max(Id),0) INTO v_newVal FROM crl_pos_log;
      v_newVal := v_newVal + 1;
      --set the sequence to that value
      LOOP
           EXIT WHEN v_incval>=v_newVal;
           SELECT crl_pos_log_Id_SEQ.nextval INTO v_incval FROM dual;
      END LOOP;
    END IF;
    --used to emulate LAST_INSERT_ID()
    --mysql_utilities.identity := v_newVal; 
   -- assign the value from the sequence to emulate the identity column
   :new.Id := v_newVal;
  END IF;
END;

/

CREATE OR REPLACE TRIGGER CRL_DEPT_STK_HIS_DEPARTMENT__1 BEFORE INSERT OR UPDATE ON crl_dept_stk_his
FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.DEPARTMENT_STOCK_HISTORY_ID IS NULL THEN
    SELECT  crl_dept_stk_his_DEPARTMENT_ST.NEXTVAL INTO v_newVal FROM DUAL;
    -- If this is the first time this table have been inserted into (sequence == 1)
    IF v_newVal = 1 THEN 
      --get the max indentity value from the table
      SELECT NVL(max(DEPARTMENT_STOCK_HISTORY_ID),0) INTO v_newVal FROM crl_dept_stk_his;
      v_newVal := v_newVal + 1;
      --set the sequence to that value
      LOOP
           EXIT WHEN v_incval>=v_newVal;
           SELECT crl_dept_stk_his_DEPARTMENT_ST.nextval INTO v_incval FROM dual;
      END LOOP;
    END IF;
    --used to emulate LAST_INSERT_ID()
    --mysql_utilities.identity := v_newVal; 
   -- assign the value from the sequence to emulate the identity column
   :new.DEPARTMENT_STOCK_HISTORY_ID := v_newVal;
  END IF;
END;

/

CREATE OR REPLACE TRIGGER CRL_MN_STK_HIS_STOCK_HISTORY_1 BEFORE INSERT OR UPDATE ON crl_mn_stk_his
FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.STOCK_HISTORY_ID IS NULL THEN
    SELECT  crl_mn_stk_his_STOCK_HISTORY_I.NEXTVAL INTO v_newVal FROM DUAL;
    -- If this is the first time this table have been inserted into (sequence == 1)
    IF v_newVal = 1 THEN 
      --get the max indentity value from the table
      SELECT NVL(max(STOCK_HISTORY_ID),0) INTO v_newVal FROM crl_mn_stk_his;
      v_newVal := v_newVal + 1;
      --set the sequence to that value
      LOOP
           EXIT WHEN v_incval>=v_newVal;
           SELECT crl_mn_stk_his_STOCK_HISTORY_I.nextval INTO v_incval FROM dual;
      END LOOP;
    END IF;
    --used to emulate LAST_INSERT_ID()
    --mysql_utilities.identity := v_newVal; 
   -- assign the value from the sequence to emulate the identity column
   :new.STOCK_HISTORY_ID := v_newVal;
  END IF;
END;

/

CREATE OR REPLACE TRIGGER TEMP_DEPT_STOCK_STATISTICS_T_4 BEFORE INSERT OR UPDATE ON temp_dept_stock_statistics
FOR EACH ROW
DECLARE 
v_newVal NUMBER(12) := 0;
v_incval NUMBER(12) := 0;
BEGIN
  IF INSERTING AND :new.temp_pri_key IS NULL THEN
    SELECT  temp_dept_stock_statistics_tem.NEXTVAL INTO v_newVal FROM DUAL;
    -- If this is the first time this table have been inserted into (sequence == 1)
    IF v_newVal = 1 THEN 
      --get the max indentity value from the table
      SELECT NVL(max(temp_pri_key),0) INTO v_newVal FROM temp_dept_stock_statistics;
      v_newVal := v_newVal + 1;
      --set the sequence to that value
      LOOP
           EXIT WHEN v_incval>=v_newVal;
           SELECT temp_dept_stock_statistics_tem.nextval INTO v_incval FROM dual;
      END LOOP;
    END IF;
    --used to emulate LAST_INSERT_ID()
    --mysql_utilities.identity := v_newVal; 
   -- assign the value from the sequence to emulate the identity column
   :new.temp_pri_key := v_newVal;
  END IF;
END;

/

DISCONNECT;
