//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSServer.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG NHẬP.
        /// </summary>
        internal static string LoginAction {
            get {
                return ResourceManager.GetString("LoginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MẬT KHẨU.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XỬ LÝ SAU KIỂM KÊ.
        /// </summary>
        internal static string StockMenu_AfterInventoryCollectorProcessing {
            get {
                return ResourceManager.GetString("StockMenu_AfterInventoryCollectorProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.NHẬN XUẤT KHO TỪ CỬA HÀNG.
        /// </summary>
        internal static string StockMenu_DepartmentStockOutConfirm {
            get {
                return ResourceManager.GetString("StockMenu_DepartmentStockOutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIỂM KÊ.
        /// </summary>
        internal static string StockMenu_InventoryCollector {
            get {
                return ResourceManager.GetString("StockMenu_InventoryCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÌM KIẾM THEO CHỦNG LOẠI.
        /// </summary>
        internal static string StockMenu_StockCategorySearch {
            get {
                return ResourceManager.GetString("StockMenu_StockCategorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHẬP HÀNG.
        /// </summary>
        internal static string StockMenu_StockIn {
            get {
                return ResourceManager.GetString("StockMenu_StockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.SÁCH LÔ HÀNG TRẢ KHO CHÍNH.
        /// </summary>
        internal static string StockMenu_StockInBackList {
            get {
                return ResourceManager.GetString("StockMenu_StockInBackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHẬP BẰNG EXCEL.
        /// </summary>
        internal static string StockMenu_StockInByExcel {
            get {
                return ResourceManager.GetString("StockMenu_StockInByExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XÁC NHẬN NHẬP KHO.
        /// </summary>
        internal static string StockMenu_StockInConfirm {
            get {
                return ResourceManager.GetString("StockMenu_StockInConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.SÁCH LÔ HÀNG NHẬP.
        /// </summary>
        internal static string StockMenu_StockInList {
            get {
                return ResourceManager.GetString("StockMenu_StockInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XUẤT HÀNG BẰNG EXCEL.
        /// </summary>
        internal static string StockMenu_StockOutByExcel {
            get {
                return ResourceManager.GetString("StockMenu_StockOutByExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XÁC NHẬN XUẤT KHO.
        /// </summary>
        internal static string StockMenu_StockOutConfirm {
            get {
                return ResourceManager.GetString("StockMenu_StockOutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH LÔ HÀNG XUẤT.
        /// </summary>
        internal static string StockMenu_StockOutList {
            get {
                return ResourceManager.GetString("StockMenu_StockOutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XUẤT HÀNG ĐẾN CỬA HÀNG.
        /// </summary>
        internal static string StockMenu_StockOutToDepartment {
            get {
                return ResourceManager.GetString("StockMenu_StockOutToDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XUẤT HÀNG ĐẾN NƠI KHÁC.
        /// </summary>
        internal static string StockMenu_StockOutToOther {
            get {
                return ResourceManager.GetString("StockMenu_StockOutToOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÌM KIẾM KHO.
        /// </summary>
        internal static string StockMenu_StockSearch {
            get {
                return ResourceManager.GetString("StockMenu_StockSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÊN NGƯỜI DÙNG.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
