//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFrame.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Distributor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Manufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Packager))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductSize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _addressField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private object[] _departmentCostsField;
        
        private long _departmentIdField;
        
        private string _departmentNameField;
        
        private object[] _employeesField;
        
        private long _exclusiveKeyField;
        
        private long _managerIdField;
        
        private object[] _scheduleTemplatesField;
        
        private System.DateTime _startDateField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        private int activeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _address
        {
            get
            {
                return this._addressField;
            }
            set
            {
                this._addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _departmentCosts
        {
            get
            {
                return this._departmentCostsField;
            }
            set
            {
                this._departmentCostsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _departmentId
        {
            get
            {
                return this._departmentIdField;
            }
            set
            {
                this._departmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _departmentName
        {
            get
            {
                return this._departmentNameField;
            }
            set
            {
                this._departmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _employees
        {
            get
            {
                return this._employeesField;
            }
            set
            {
                this._employeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _managerId
        {
            get
            {
                return this._managerIdField;
            }
            set
            {
                this._managerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _scheduleTemplates
        {
            get
            {
                return this._scheduleTemplatesField;
            }
            set
            {
                this._scheduleTemplatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _startDate
        {
            get
            {
                return this._startDateField;
            }
            set
            {
                this._startDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentStockOut", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Distributor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Manufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Packager))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductSize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class DepartmentStockOut : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private long _departmentIdField;
        
        private object[] _departmentStockOutCostsField;
        
        private object[] _departmentStockOutDetailsField;
        
        private long _exclusiveKeyField;
        
        private System.DateTime _stockOutDateField;
        
        private long _stockOutIdField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        private long ConfirmFlgk__BackingFieldField;
        
        private AppFrame.Model.StockDefectStatus DefectStatusk__BackingFieldField;
        
        private AppFrame.Model.DepartmentStockOutPK DepartmentStockOutPKk__BackingFieldField;
        
        private long OtherDepartmentIdk__BackingFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _departmentId
        {
            get
            {
                return this._departmentIdField;
            }
            set
            {
                this._departmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _departmentStockOutCosts
        {
            get
            {
                return this._departmentStockOutCostsField;
            }
            set
            {
                this._departmentStockOutCostsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _departmentStockOutDetails
        {
            get
            {
                return this._departmentStockOutDetailsField;
            }
            set
            {
                this._departmentStockOutDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _stockOutDate
        {
            get
            {
                return this._stockOutDateField;
            }
            set
            {
                this._stockOutDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _stockOutId
        {
            get
            {
                return this._stockOutIdField;
            }
            set
            {
                this._stockOutIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ConfirmFlg>k__BackingField", IsRequired=true)]
        public long ConfirmFlgk__BackingField
        {
            get
            {
                return this.ConfirmFlgk__BackingFieldField;
            }
            set
            {
                this.ConfirmFlgk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DefectStatus>k__BackingField", IsRequired=true)]
        public AppFrame.Model.StockDefectStatus DefectStatusk__BackingField
        {
            get
            {
                return this.DefectStatusk__BackingFieldField;
            }
            set
            {
                this.DefectStatusk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DepartmentStockOutPK>k__BackingField", IsRequired=true)]
        public AppFrame.Model.DepartmentStockOutPK DepartmentStockOutPKk__BackingField
        {
            get
            {
                return this.DepartmentStockOutPKk__BackingFieldField;
            }
            set
            {
                this.DepartmentStockOutPKk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OtherDepartmentId>k__BackingField", IsRequired=true)]
        public long OtherDepartmentIdk__BackingField
        {
            get
            {
                return this.OtherDepartmentIdk__BackingFieldField;
            }
            set
            {
                this.OtherDepartmentIdk__BackingFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockDefectStatus", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    public partial class StockDefectStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long DefectStatusIdk__BackingFieldField;
        
        private string DefectStatusNamek__BackingFieldField;
        
        private string testField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DefectStatusId>k__BackingField", IsRequired=true)]
        public long DefectStatusIdk__BackingField
        {
            get
            {
                return this.DefectStatusIdk__BackingFieldField;
            }
            set
            {
                this.DefectStatusIdk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DefectStatusName>k__BackingField", IsRequired=true)]
        public string DefectStatusNamek__BackingField
        {
            get
            {
                return this.DefectStatusNamek__BackingFieldField;
            }
            set
            {
                this.DefectStatusNamek__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string test
        {
            get
            {
                return this.testField;
            }
            set
            {
                this.testField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentStockOutPK", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    public partial class DepartmentStockOutPK : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long DepartmentIdk__BackingFieldField;
        
        private long StockOutIdk__BackingFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DepartmentId>k__BackingField", IsRequired=true)]
        public long DepartmentIdk__BackingField
        {
            get
            {
                return this.DepartmentIdk__BackingFieldField;
            }
            set
            {
                this.DepartmentIdk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StockOutId>k__BackingField", IsRequired=true)]
        public long StockOutIdk__BackingField
        {
            get
            {
                return this.StockOutIdk__BackingFieldField;
            }
            set
            {
                this.StockOutIdk__BackingFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentPrice", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    public partial class DepartmentPrice : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private long _exclusiveKeyField;
        
        private long _priceField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        private AppFrame.Model.DepartmentPricePK DepartmentPricePKk__BackingFieldField;
        
        private AppFrame.Model.Department Departmentk__BackingFieldField;
        
        private AppFrame.Model.ProductMaster ProductMasterk__BackingFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _price
        {
            get
            {
                return this._priceField;
            }
            set
            {
                this._priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DepartmentPricePK>k__BackingField", IsRequired=true)]
        public AppFrame.Model.DepartmentPricePK DepartmentPricePKk__BackingField
        {
            get
            {
                return this.DepartmentPricePKk__BackingFieldField;
            }
            set
            {
                this.DepartmentPricePKk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Department>k__BackingField", IsRequired=true)]
        public AppFrame.Model.Department Departmentk__BackingField
        {
            get
            {
                return this.Departmentk__BackingFieldField;
            }
            set
            {
                this.Departmentk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProductMaster>k__BackingField", IsRequired=true)]
        public AppFrame.Model.ProductMaster ProductMasterk__BackingField
        {
            get
            {
                return this.ProductMasterk__BackingFieldField;
            }
            set
            {
                this.ProductMasterk__BackingFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentPricePK", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    public partial class DepartmentPricePK : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long DepartmentIdk__BackingFieldField;
        
        private string ProductMasterIdk__BackingFieldField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DepartmentId>k__BackingField", IsRequired=true)]
        public long DepartmentIdk__BackingField
        {
            get
            {
                return this.DepartmentIdk__BackingFieldField;
            }
            set
            {
                this.DepartmentIdk__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProductMasterId>k__BackingField", IsRequired=true)]
        public string ProductMasterIdk__BackingField
        {
            get
            {
                return this.ProductMasterIdk__BackingFieldField;
            }
            set
            {
                this.ProductMasterIdk__BackingFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductMaster", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Distributor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Manufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Packager))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductSize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class ProductMaster : AppFrame.Common.ClonableObject
    {
        
        private AppFrame.Model.Category _categoryField;
        
        private AppFrame.Model.Country _countryField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private string _descriptionField;
        
        private AppFrame.Model.Distributor _distributorField;
        
        private long _exclusiveKeyField;
        
        private AppFrame.Model.Manufacturer _manufacturerField;
        
        private AppFrame.Model.Packager _packagerField;
        
        private AppFrame.Model.ProductColor _productColorField;
        
        private string _productFullNameField;
        
        private string _productMasterIdField;
        
        private string _productNameField;
        
        private AppFrame.Model.ProductSize _productSizeField;
        
        private AppFrame.Model.ProductType _productTypeField;
        
        private object[] _productsField;
        
        private long _supplierIdField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        private string Barcodek__BackingFieldField;
        
        private string ImagePathk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppFrame.Model.Category _category
        {
            get
            {
                return this._categoryField;
            }
            set
            {
                this._categoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppFrame.Model.Country _country
        {
            get
            {
                return this._countryField;
            }
            set
            {
                this._countryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _description
        {
            get
            {
                return this._descriptionField;
            }
            set
            {
                this._descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppFrame.Model.Distributor _distributor
        {
            get
            {
                return this._distributorField;
            }
            set
            {
                this._distributorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppFrame.Model.Manufacturer _manufacturer
        {
            get
            {
                return this._manufacturerField;
            }
            set
            {
                this._manufacturerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppFrame.Model.Packager _packager
        {
            get
            {
                return this._packagerField;
            }
            set
            {
                this._packagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppFrame.Model.ProductColor _productColor
        {
            get
            {
                return this._productColorField;
            }
            set
            {
                this._productColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _productFullName
        {
            get
            {
                return this._productFullNameField;
            }
            set
            {
                this._productFullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _productMasterId
        {
            get
            {
                return this._productMasterIdField;
            }
            set
            {
                this._productMasterIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _productName
        {
            get
            {
                return this._productNameField;
            }
            set
            {
                this._productNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppFrame.Model.ProductSize _productSize
        {
            get
            {
                return this._productSizeField;
            }
            set
            {
                this._productSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppFrame.Model.ProductType _productType
        {
            get
            {
                return this._productTypeField;
            }
            set
            {
                this._productTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _products
        {
            get
            {
                return this._productsField;
            }
            set
            {
                this._productsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _supplierId
        {
            get
            {
                return this._supplierIdField;
            }
            set
            {
                this._supplierIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Barcode>k__BackingField", IsRequired=true)]
        public string Barcodek__BackingField
        {
            get
            {
                return this.Barcodek__BackingFieldField;
            }
            set
            {
                this.Barcodek__BackingFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ImagePath>k__BackingField", IsRequired=true)]
        public string ImagePathk__BackingField
        {
            get
            {
                return this.ImagePathk__BackingFieldField;
            }
            set
            {
                this.ImagePathk__BackingFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Distributor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Manufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Packager))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductSize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long _categoryIdField;
        
        private string _categoryNameField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private long _exclusiveKeyField;
        
        private long _parentCategoryIdField;
        
        private object[] _productMastersField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _categoryId
        {
            get
            {
                return this._categoryIdField;
            }
            set
            {
                this._categoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _categoryName
        {
            get
            {
                return this._categoryNameField;
            }
            set
            {
                this._categoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _parentCategoryId
        {
            get
            {
                return this._parentCategoryIdField;
            }
            set
            {
                this._parentCategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _productMasters
        {
            get
            {
                return this._productMastersField;
            }
            set
            {
                this._productMastersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Distributor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Manufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Packager))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductSize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long _countryIdField;
        
        private string _countryNameField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private long _exclusiveKeyField;
        
        private object[] _productMastersField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _countryId
        {
            get
            {
                return this._countryIdField;
            }
            set
            {
                this._countryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _countryName
        {
            get
            {
                return this._countryNameField;
            }
            set
            {
                this._countryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _productMasters
        {
            get
            {
                return this._productMastersField;
            }
            set
            {
                this._productMastersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distributor", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Manufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Packager))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductSize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class Distributor : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private long _distributorIdField;
        
        private string _distributorNameField;
        
        private long _exclusiveKeyField;
        
        private object[] _productMastersField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _distributorId
        {
            get
            {
                return this._distributorIdField;
            }
            set
            {
                this._distributorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _distributorName
        {
            get
            {
                return this._distributorNameField;
            }
            set
            {
                this._distributorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _productMasters
        {
            get
            {
                return this._productMastersField;
            }
            set
            {
                this._productMastersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manufacturer", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Distributor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Packager))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductSize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class Manufacturer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private long _exclusiveKeyField;
        
        private long _manufacturerIdField;
        
        private string _manufacturerNameField;
        
        private object[] _productMastersField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _manufacturerId
        {
            get
            {
                return this._manufacturerIdField;
            }
            set
            {
                this._manufacturerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _manufacturerName
        {
            get
            {
                return this._manufacturerNameField;
            }
            set
            {
                this._manufacturerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _productMasters
        {
            get
            {
                return this._productMastersField;
            }
            set
            {
                this._productMastersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Packager", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Distributor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Manufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductSize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class Packager : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private long _exclusiveKeyField;
        
        private long _packagerIdField;
        
        private string _packagerNameField;
        
        private object[] _productMastersField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _packagerId
        {
            get
            {
                return this._packagerIdField;
            }
            set
            {
                this._packagerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _packagerName
        {
            get
            {
                return this._packagerNameField;
            }
            set
            {
                this._packagerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _productMasters
        {
            get
            {
                return this._productMastersField;
            }
            set
            {
                this._productMastersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductColor", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Distributor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Manufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Packager))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductSize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class ProductColor : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long _colorIdField;
        
        private string _colorNameField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private long _exclusiveKeyField;
        
        private object[] _productMastersField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _colorId
        {
            get
            {
                return this._colorIdField;
            }
            set
            {
                this._colorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _colorName
        {
            get
            {
                return this._colorNameField;
            }
            set
            {
                this._colorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _productMasters
        {
            get
            {
                return this._productMastersField;
            }
            set
            {
                this._productMastersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSize", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Distributor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Manufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Packager))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class ProductSize : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private long _exclusiveKeyField;
        
        private object[] _productMastersField;
        
        private long _sizeIdField;
        
        private string _sizeNameField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _productMasters
        {
            get
            {
                return this._productMastersField;
            }
            set
            {
                this._productMastersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _sizeId
        {
            get
            {
                return this._sizeIdField;
            }
            set
            {
                this._sizeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _sizeName
        {
            get
            {
                return this._sizeNameField;
            }
            set
            {
                this._sizeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductType", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Department))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.StockDefectStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentStockOutPK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPrice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.DepartmentPricePK))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Distributor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Manufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.Packager))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductSize))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Common.ClonableObject))]
    public partial class ProductType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime _createDateField;
        
        private string _createIdField;
        
        private long _delFlgField;
        
        private long _exclusiveKeyField;
        
        private object[] _productMastersField;
        
        private long _typeIdField;
        
        private string _typeNameField;
        
        private System.DateTime _updateDateField;
        
        private string _updateIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _createDate
        {
            get
            {
                return this._createDateField;
            }
            set
            {
                this._createDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _createId
        {
            get
            {
                return this._createIdField;
            }
            set
            {
                this._createIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _delFlg
        {
            get
            {
                return this._delFlgField;
            }
            set
            {
                this._delFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _exclusiveKey
        {
            get
            {
                return this._exclusiveKeyField;
            }
            set
            {
                this._exclusiveKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _productMasters
        {
            get
            {
                return this._productMastersField;
            }
            set
            {
                this._productMastersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long _typeId
        {
            get
            {
                return this._typeIdField;
            }
            set
            {
                this._typeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _typeName
        {
            get
            {
                return this._typeNameField;
            }
            set
            {
                this._typeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _updateDate
        {
            get
            {
                return this._updateDateField;
            }
            set
            {
                this._updateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _updateId
        {
            get
            {
                return this._updateIdField;
            }
            set
            {
                this._updateIdField = value;
            }
        }
    }
}
namespace AppFrame.Common
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClonableObject", Namespace="http://schemas.datacontract.org/2004/07/AppFrame.Common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AppFrame.Model.ProductMaster))]
    public partial class ClonableObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8001/ServerService/", ConfigurationName="ServerService", CallbackContract=typeof(ServerServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface ServerService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8001/ServerService/ServerService/JoinDistributingGroup", ReplyAction="http://localhost:8001/ServerService/ServerService/JoinDistributingGroupResponse")]
    void JoinDistributingGroup(AppFrame.Model.Department department);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://localhost:8001/ServerService/ServerService/MakeDepartmentStockOut")]
    void MakeDepartmentStockOut(AppFrame.Model.Department department, AppFrame.Model.DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://localhost:8001/ServerService/ServerService/ExitDistributingGroup")]
    void ExitDistributingGroup(AppFrame.Model.Department department);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ServerServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://localhost:8001/ServerService/ServerService/NotifyNewDepartmentStockOut")]
    void NotifyNewDepartmentStockOut(AppFrame.Model.Department department, AppFrame.Model.DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://localhost:8001/ServerService/ServerService/NotifyConnected")]
    void NotifyConnected();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ServerServiceChannel : ServerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServerServiceClient : System.ServiceModel.DuplexClientBase<ServerService>, ServerService
{
    
    public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void JoinDistributingGroup(AppFrame.Model.Department department)
    {
        base.Channel.JoinDistributingGroup(department);
    }
    
    public void MakeDepartmentStockOut(AppFrame.Model.Department department, AppFrame.Model.DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price)
    {
        base.Channel.MakeDepartmentStockOut(department, stockOut, price);
    }
    
    public void ExitDistributingGroup(AppFrame.Model.Department department)
    {
        base.Channel.ExitDistributingGroup(department);
    }
}
