CREATE TABLE `pos`.`sub_stock` (
  `SUB_STOCK_ID` INTEGER UNSIGNED NOT NULL,
  `PRODUCT_ID` VARCHAR(20) NOT NULL,
  `PRODUCT_MASTER_ID` VARCHAR(13),
  `QUANTITY` VARCHAR(45) NOT NULL,
  `CREATE_DATE` DATETIME,
  `CREATE_ID` VARCHAR(50),
  `UPDATE_DATE` DATETIME,
  `UPDATE_ID` VARCHAR(50),
  `EXCLUSIVE_KEY` INTEGER UNSIGNED DEFAULT 0,
  `DEL_FLG` INTEGER UNSIGNED DEFAULT 0,
  `GOOD_QUANTITY` INTEGER UNSIGNED DEFAULT 0,
  `ERROR_QUANTITY` INTEGER UNSIGNED DEFAULT 0,
  `DAMAGE_QUANTITY` INTEGER UNSIGNED DEFAULT 0,
  `LOST_QUANTITY` INTEGER UNSIGNED DEFAULT 0,
  `UNCONFIRM_QUANTITY` INTEGER UNSIGNED DEFAULT 0,
  PRIMARY KEY (`SUB_STOCK_ID`, `PRODUCT_ID`, `PRODUCT_MASTER_ID`),
  CONSTRAINT `FK_sub_stock_1` FOREIGN KEY `FK_sub_stock_1` (`PRODUCT_ID`)
    REFERENCES `product` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_sub_stock_2` FOREIGN KEY `FK_sub_stock_2` (`PRODUCT_MASTER_ID`)
    REFERENCES `product_master` (`PRODUCT_MASTER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_general_ci;