//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AppFrameClient.Services
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://localhost:8001/", ConfigurationName = "ServerService", CallbackContract = typeof(ServerServiceCallback), SessionMode = System.ServiceModel.SessionMode.Required)]
    public interface ServerService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://localhost:8001/ServerService/JoinDistributingGroup", ReplyAction = "http://localhost:8001/ServerService/ServerService/JoinDistributingGroupResponse")]
        void JoinDistributingGroup(AppFrame.Model.Department department);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/MakeDepartmentStockOut")]
        void MakeDepartmentStockOut(AppFrame.Model.Department department, AppFrame.Model.DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/ExitDistributingGroup")]
        void ExitDistributingGroup(AppFrame.Model.Department department);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServerServiceCallback
    {

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyNewDepartmentStockOut")]
        void NotifyNewDepartmentStockOut(AppFrame.Model.Department department, AppFrame.Model.DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyConnected")]
        void NotifyConnected();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServerServiceChannel : ServerService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.DuplexClientBase<ServerService>, ServerService
    {

        public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance) :
            base(callbackInstance)
        {
        }

        public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
            base(callbackInstance, endpointConfigurationName)
        {
        }

        public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
            base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }

        public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }

        public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(callbackInstance, binding, remoteAddress)
        {
        }

        public void JoinDistributingGroup(AppFrame.Model.Department department)
        {
            base.Channel.JoinDistributingGroup(department);
        }

        public void MakeDepartmentStockOut(AppFrame.Model.Department department, AppFrame.Model.DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price)
        {
            base.Channel.MakeDepartmentStockOut(department, stockOut, price);
        }

        public void ExitDistributingGroup(AppFrame.Model.Department department)
        {
            base.Channel.ExitDistributingGroup(department);
        }
}
}