//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using AppFrame.Model;

namespace AppFrameClient.Services
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://localhost:8001/", ConfigurationName = "ServerService", CallbackContract = typeof(ServerServiceCallback), SessionMode = System.ServiceModel.SessionMode.Required)]
    public interface ServerService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://localhost:8001/ServerService/JoinDistributingGroup", ReplyAction = "http://localhost:8001/ServerService/JoinDistributingGroupResponse")]
        void JoinDistributingGroup(Department department);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/MakeDepartmentStockOut")]
        void MakeDepartmentStockOut(Department department, DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price);

        [System.ServiceModel.OperationContractAttribute(Action = "http://localhost:8001/ServerService/MakeRawDepartmentStockOut", ReplyAction = "http://localhost:8001/ServerService/MakeRawDepartmentStockOutResponse")]
        void MakeRawDepartmentStockOut(Department department, DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/MakeMultiDepartmentStockOut")]
        void MakeMultiDepartmentStockOut(Department department, DepartmentStockOut[] stockOutList, AppFrame.Model.DepartmentPrice price);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/MakeDepartmentStockIn")]
        void MakeDepartmentStockIn(Department department, DepartmentStockIn stockOut);

        [System.ServiceModel.OperationContractAttribute(Action = "http://localhost:8001/ServerService/MakeRawDepartmentStockIn", ReplyAction = "http://localhost:8001/ServerService/MakeRawDepartmentStockInResponse")]
        void MakeRawDepartmentStockIn(Department department, DepartmentStockIn stockOut);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/ExitDistributingGroup")]
        void ExitDistributingGroup(Department department);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/RequestDepartmentStockOut")]
        void RequestDepartmentStockOut(long departmentId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/RequestRawDepartmentStockOut")]
        void RequestRawDepartmentStockOut(long departmentId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/RequestRawDepartmentStockIn")]
        void RequestRawDepartmentStockIn(long departmentId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/RequestDepartmentStockIn")]
        void RequestDepartmentStockIn(long departmentId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://localhost:8001/ServerService/MakeAllShoesDepartmentStockInBack", ReplyAction = "http://localhost:8001/ServerService/MakeAllShoesDepartmentStockInBackResponse")]
        DepartmentStockIn MakeAllShoesDepartmentStockInBack(long salePointId, long subStockId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/InformMessage")]
        void InformMessage(long destDeptId, bool isError, string message);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/InformDepartmentStockOutSuccess")]
        void InformDepartmentStockOutSuccess(long sourceDeptId, long destDeptId, long deptStockId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/InformDepartmentStockOutFail")]
        void InformDepartmentStockOutFail(long sourceDeptId, long destDeptId, long deptStockId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/InformDepartmentStockInSuccess")]
        void InformDepartmentStockInSuccess(Department department, DepartmentStockIn stockIn, long stockOutId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/InformMultiDepartmentStockInSuccess")]
        void InformMultiDepartmentStockInSuccess(Department department, DepartmentStockIn[] stockIn, long stockOutId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/InformDepartmentStockInFail")]
        void InformDepartmentStockInFail(Department department, DepartmentStockIn stockIn, long stockOutId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/UpdateStockInBackFlag")]
        void UpdateStockInBackFlag(Department department, DepartmentStockIn stockIn, long stockOutId);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServerServiceCallback
    {

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyNewDepartmentStockOut")]
        void NotifyNewDepartmentStockOut(Department department, DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyNewDepartmentStockIn")]
        void NotifyNewDepartmentStockIn(Department department, DepartmentStockIn stockOut);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyConnected")]
        void NotifyConnected();

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyStockOutSuccess")]
        void NotifyStockOutSuccess(long sourceDeptId, long deptDeptId, long stockOutId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyStockInSuccess")]
        void NotifyStockInSuccess(Department department, DepartmentStockIn stockIn, long stockOutId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyUpdateStockOutFlag")]
        void NotifyUpdateStockOutFlag(Department department, DepartmentStockIn stockIn, long stockOutId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyRequestDepartmentStockOut")]
        void NotifyRequestDepartmentStockOut(long departmentId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyRequestDepartmentStockIn")]
        void NotifyRequestDepartmentStockIn(long departmentId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyNewMultiDepartmentStockOut")]
        void NotifyNewMultiDepartmentStockOut(Department department, DepartmentStockOut[] list, AppFrame.Model.DepartmentPrice price);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyMultiStockInSuccess")]
        void NotifyMultiStockInSuccess(Department department, DepartmentStockIn[] stockInList, long id);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyStockInFail")]
        void NotifyStockInFail(Department department, DepartmentStockIn stockIn, long id);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyStockOutFail")]
        void NotifyStockOutFail(long sourceId, long destId, long stockId);

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://localhost:8001/ServerService/NotifyInformMessage")]
        void NotifyInformMessage(long destDeptId, bool isError, string message);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServerServiceChannel : ServerService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.DuplexClientBase<ServerService>, ServerService
    {

        public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance) :
            base(callbackInstance)
        {
        }

        public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
            base(callbackInstance, endpointConfigurationName)
        {
        }

        public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
            base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }

        public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }

        public ServerServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(callbackInstance, binding, remoteAddress)
        {
        }

        public void JoinDistributingGroup(Department department)
        {
            base.Channel.JoinDistributingGroup(department);
        }

        public void MakeDepartmentStockOut(Department department, DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price)
        {
            base.Channel.MakeDepartmentStockOut(department, stockOut, price);
        }

        public void MakeRawDepartmentStockOut(Department department, DepartmentStockOut stockOut, AppFrame.Model.DepartmentPrice price)
        {
            base.Channel.MakeRawDepartmentStockOut(department, stockOut, price);
        }

        public void MakeMultiDepartmentStockOut(Department department, DepartmentStockOut[] stockOutList, AppFrame.Model.DepartmentPrice price)
        {
            base.Channel.MakeMultiDepartmentStockOut(department, stockOutList, price);
        }

        public void MakeDepartmentStockIn(Department department, DepartmentStockIn stockOut)
        {
            base.Channel.MakeDepartmentStockIn(department, stockOut);
        }

        public void MakeRawDepartmentStockIn(Department department, DepartmentStockIn stockOut)
        {
            base.Channel.MakeRawDepartmentStockIn(department, stockOut);
        }

        public void ExitDistributingGroup(Department department)
        {
            base.Channel.ExitDistributingGroup(department);
        }

        public void RequestDepartmentStockOut(long departmentId)
        {
            base.Channel.RequestDepartmentStockOut(departmentId);
        }

        public void RequestRawDepartmentStockOut(long departmentId)
        {
            base.Channel.RequestRawDepartmentStockOut(departmentId);
        }

        public void RequestRawDepartmentStockIn(long departmentId)
        {
            base.Channel.RequestRawDepartmentStockIn(departmentId);
        }

        public void RequestDepartmentStockIn(long departmentId)
        {
            base.Channel.RequestDepartmentStockIn(departmentId);
        }

        public DepartmentStockIn MakeAllShoesDepartmentStockInBack(long salePointId, long subStockId)
        {
            return base.Channel.MakeAllShoesDepartmentStockInBack(salePointId, subStockId);
        }

        public void InformMessage(long destDeptId, bool isError, string message)
        {
            base.Channel.InformMessage(destDeptId, isError, message);
        }

        public void InformDepartmentStockOutSuccess(long sourceDeptId, long destDeptId, long deptStockId)
        {
            base.Channel.InformDepartmentStockOutSuccess(sourceDeptId, destDeptId, deptStockId);
        }

        public void InformDepartmentStockOutFail(long sourceDeptId, long destDeptId, long deptStockId)
        {
            base.Channel.InformDepartmentStockOutFail(sourceDeptId, destDeptId, deptStockId);
        }

        public void InformDepartmentStockInSuccess(Department department, DepartmentStockIn stockIn, long stockOutId)
        {
            base.Channel.InformDepartmentStockInSuccess(department, stockIn, stockOutId);
        }

        public void InformMultiDepartmentStockInSuccess(Department department, DepartmentStockIn[] stockIn, long stockOutId)
        {
            base.Channel.InformMultiDepartmentStockInSuccess(department, stockIn, stockOutId);
        }

        public void InformDepartmentStockInFail(Department department, DepartmentStockIn stockIn, long stockOutId)
        {
            base.Channel.InformDepartmentStockInFail(department, stockIn, stockOutId);
        }

        public void UpdateStockInBackFlag(Department department, DepartmentStockIn stockIn, long stockOutId)
        {
            base.Channel.UpdateStockInBackFlag(department, stockIn, stockOutId);
        }
    }

}